import CoopConfiguration
import CoopCore
import Foundation
import Synchronization
import Testing

@testable import CoopHost

// MARK: - Helpers

/// Collects diagnostics lines (message part only).
final class DiagnosticsLog: Sendable {
  private let lines = Mutex<[String]>([])
  var all: [String] { lines.withLock { $0 } }
  var diagnostics: Diagnostics {
    Diagnostics(verbosity: 1) { line in
      let message = line.range(of: " coop: ").map { String(line[$0.upperBound...]) } ?? line
      self.lines.withLock { $0.append(message) }
    }
  }
  func contains(_ text: String) -> Bool { all.contains { $0.contains(text) } }
}

func temporaryDirectory(_ label: String) throws -> String {
  let path = FileManager.default.temporaryDirectory.appending(
    path: "coop-\(label)-\(UUID().uuidString)"
  ).path
  try FileManager.default.createDirectory(atPath: path, withIntermediateDirectories: true)
  // Canonical (`/private/var/...`) so expected paths match realpath.
  return URL(fileURLWithPath: path).resolvingSymlinksInPath().path
}

func writeUpdateFile(_ path: String, _ text: String, mode: Int = 0o644) throws {
  try FileManager.default.createDirectory(
    atPath: (path as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
  try Data(text.utf8).write(to: URL(fileURLWithPath: path))
  chmod(path, mode_t(mode))
}

func readText(_ path: String) -> String? { try? String(contentsOfFile: path, encoding: .utf8) }

private let releaseBuild = CoopBuild(version: "0.6.0", kind: .release, versionString: "0.6.0")

// MARK: - Tags, names and checksums

@Test func stripVRemovesOneLeadingV() {
  #expect(UpdateChannel.stripV("v0.3.1") == "0.3.1")
  #expect(UpdateChannel.stripV("0.3.1") == "0.3.1")
  #expect(UpdateChannel.stripV("v") == "")
}

@Test func normalizeTagAddsVAndRejectsNonSemver() throws {
  #expect(try UpdateChannel.normalizeTag("0.3.1") == "v0.3.1")
  #expect(try UpdateChannel.normalizeTag("v0.3.1") == "v0.3.1")
  #expect(try UpdateChannel.normalizeTag(" 0.3.1 ") == "v0.3.1")
  #expect(try UpdateChannel.normalizeTag("0.3.1-rc.1") == "v0.3.1-rc.1")
  // The tag is interpolated into the API URL path: no traversal.
  for bad in [
    "../attacker/evil/releases/latest", "latest", "0.3.1/../evil", "", "v", "not-a-version",
  ] {
    #expect(throws: (any Error).self) { try UpdateChannel.normalizeTag(bad) }
  }
  do {
    _ = try UpdateChannel.normalizeTag("latest")
    Issue.record("accepted")
  } catch {
    #expect(
      "\(error)"
        == "--version \"latest\" is not a valid semver tag\n\nCaused by:\n    unexpected character 'l' while parsing major version number"
    )
  }
}

@Test func assetNameMatchesReleaseWorkflowNaming() throws {
  #expect(
    UpdateChannel.assetName(tag: "v0.3.1", triple: "aarch64-apple-darwin")
      == "coop-v0.3.1-aarch64-apple-darwin.tar.gz")
  #expect(try UpdateChannel.targetTriple() == "aarch64-apple-darwin")
}

@Test func checksumsParseLikeSha256sum() throws {
  let b = String(repeating: "b", count: 64)
  #expect(
    Checksums.parse(
      "\(String(repeating: "a", count: 64))  other.tar.gz\n\(b)  coop-v1.tar.gz\n",
      file: "coop-v1.tar.gz")?.rawValue == b)
  let c = String(repeating: "c", count: 64)
  #expect(Checksums.parse("\(c) *coop.tar.gz\n", file: "coop.tar.gz")?.rawValue == c)
  let d = String(repeating: "d", count: 64)
  #expect(
    Checksums.parse("\n# generated by release.yml\n\(d)  x.tar.gz\n", file: "x.tar.gz")?.rawValue
      == d)
  #expect(
    Checksums.parse("\(String(repeating: "e", count: 64))  other.tar.gz\n", file: "coop.tar.gz")
      == nil)
  #expect(Checksums.parse("abcd  x.tar.gz\n", file: "x.tar.gz") == nil)
  #expect(
    Checksums.parse("\(String(repeating: "z", count: 64))  x.tar.gz\n", file: "x.tar.gz") == nil)
  let one = String(repeating: "1", count: 64)
  #expect(
    Checksums.parse(
      "\(one)  x.tar.gz\n\(String(repeating: "2", count: 64))  x.tar.gz\n", file: "x.tar.gz")?
      .rawValue == one)
  let three = String(repeating: "3", count: 64)
  #expect(Checksums.parse("\(three)  x.tar.gz\r\n", file: "x.tar.gz")?.rawValue == three)
  // Upper-case digests compare equal to the computed lower-case digest.
  #expect(
    Checksums.parse("\(String(repeating: "A", count: 64))  x\n", file: "x")
      == (try SHA256Hex(String(repeating: "a", count: 64))))
}

@Test func semverOrderingMatchesTheRustCrate() throws {
  func v(_ text: String) throws -> SemanticVersion { try SemanticVersion(parsing: text) }
  #expect(try v("0.3.2") > v("0.3.1"))
  #expect(try v("0.4.0") > v("0.4.0-rc.1"))
  #expect(try v("0.4.0-rc.1") > v("0.3.2"))
  #expect(try v("1.0.0-alpha") < v("1.0.0-alpha.1"))
  #expect(try v("1.0.0-alpha.1") < v("1.0.0-alpha.beta"))
  #expect(try v("1.0.0-beta.2") < v("1.0.0-beta.11"))
  #expect(try v("1.0.0-rc.1") < v("1.0.0"))
  #expect(try v("1.0.0") < v("1.0.0+build"))
  #expect(try v("1.2.3-rc.1+b.5").description == "1.2.3-rc.1+b.5")
  for (bad, message) in [
    ("", "empty string, expected a semver version"),
    ("01.0.0", "invalid leading zero in major version number"),
    ("1.0", "unexpected end of input while parsing minor version number"),
    ("1.0.0-01", "invalid leading zero in pre-release identifier"),
    ("1.0.0-", "empty identifier segment in pre-release identifier"),
    ("1.0.0/x", "unexpected character '/' after patch version number"),
  ] {
    #expect(throws: SemanticVersion.ParseError(description: message)) { try v(bad) }
  }
}

@Test func verifySHA256AcceptsTheRightDigestOnly() throws {
  let directory = try temporaryDirectory("sha")
  defer { try? FileManager.default.removeItem(atPath: directory) }
  let path = directory + "/payload"
  try writeUpdateFile(path, "hello world")
  try Updater.verifySHA256(
    path, expected: SHA256Hex("b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"))
  #expect(throws: (any Error).self) {
    try Updater.verifySHA256(path, expected: SHA256Hex(String(repeating: "0", count: 64)))
  }
}

// MARK: - Provenance and auth selection

@Test func attestationArgumentsPinTheRepository() {
  let pinned = [
    "attestation", "verify", "/tmp/coop.tar.gz", "--repo", "chr33s/coop", "--cert-identity",
    "https://github.com/chr33s/coop/.github/workflows/release.yml@refs/tags/v1.2.3",
    "--source-ref", "refs/tags/v1.2.3", "--deny-self-hosted-runners",
  ]
  #expect(
    Provenance.verifyArguments(tarball: "/tmp/coop.tar.gz", bundle: nil, tag: "v1.2.3") == pinned)
  #expect(
    Provenance.verifyArguments(
      tarball: "/tmp/coop.tar.gz", bundle: "/tmp/attestations.jsonl", tag: "v1.2.3")
      == pinned + ["--bundle", "/tmp/attestations.jsonl"])
}

/// `candidate.yml` also holds `attestations: write`; the pin must name the
/// release workflow, and the release workflow must be the one that attests.
@Test func signerWorkflowIsTheReleaseWorkflow() throws {
  let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    .appending(path: "../../..").standardized.path
  let workflow = try String(
    contentsOfFile: root + "/" + UpdateChannel.signerWorkflow, encoding: .utf8)
  #expect(workflow.contains("actions/attest-build-provenance@"))
  #expect(workflow.contains("\n      - \"v*\"\n"))
  #expect(UpdateChannel.signerWorkflow != ".github/workflows/candidate.yml")
}

private let bundleAsset = Release.Asset(name: "attestations.jsonl", url: "https://example.com/B")
private let withBundle = Release(
  tag: "v9.9.9",
  assets: [Release.Asset(name: "SHA256SUMS", url: "https://example.com/S"), bundleAsset])
private let withoutBundle = Release(
  tag: "v0.5.4", assets: [Release.Asset(name: "SHA256SUMS", url: "https://example.com/S")])

@Test func bundleDecisionOrder() {
  #expect(BundleDecision.decide(withBundle, apiOverridden: true, ghPresent: true) == .testMode)
  #expect(BundleDecision.decide(withBundle, apiOverridden: false, ghPresent: false) == .noGh)
  #expect(BundleDecision.decide(withBundle, apiOverridden: true, ghPresent: false) == .testMode)
  #expect(
    BundleDecision.decide(withBundle, apiOverridden: false, ghPresent: true) == .fetch(bundleAsset))
  #expect(BundleDecision.decide(withoutBundle, apiOverridden: false, ghPresent: true) == .noAsset)
}

@Test func provenanceNamesTheFallbackThatHappened() {
  #expect(Provenance.bundle("/tmp/b.jsonl").bundlePath == "/tmp/b.jsonl")
  for other in [Provenance.testMode, .noGh, .api(.noAsset)] { #expect(other.bundlePath == nil) }
  #expect(
    Provenance.api(.noAsset).apiFallbackHint.contains("the release publishes no attestations.jsonl")
  )
  #expect(
    Provenance.api(.downloadFailed).apiFallbackHint.contains(
      "attestations.jsonl could not be downloaded"))
  #expect(
    Provenance.api(.emptyBundle).apiFallbackHint.contains(
      "the published attestations.jsonl is empty"))
  for none in [Provenance.bundle("/b"), .testMode, .noGh] { #expect(none.apiFallbackHint == "") }
}

@Test func authStrategySelection() {
  #expect(
    AuthStrategy.select(apiBaseOverridden: true, hasGh: true, ghAuthenticated: true, token: "t")
      == .curlBare)
  #expect(
    AuthStrategy.select(apiBaseOverridden: false, hasGh: true, ghAuthenticated: true, token: "t")
      == .gh)
  #expect(
    AuthStrategy.select(apiBaseOverridden: false, hasGh: true, ghAuthenticated: false, token: "abc")
      == .curlBearer("abc"))
  #expect(
    AuthStrategy.select(
      apiBaseOverridden: false, hasGh: false, ghAuthenticated: false, token: "abc")
      == .curlBearer("abc"))
  #expect(
    AuthStrategy.select(apiBaseOverridden: false, hasGh: false, ghAuthenticated: false, token: nil)
      == .curlBare)
  #expect(
    AuthStrategy.select(apiBaseOverridden: false, hasGh: false, ghAuthenticated: false, token: "")
      == .curlBare)
}

@Test func releaseDecodesGitHubShape() throws {
  let release = try Release.parse(
    #"{"tag_name": "v9.9.9", "draft": false, "assets": [{"name": "x.tar.gz", "browser_download_url": "https://example.com/x.tar.gz", "size": 3}]}"#
  )
  #expect(
    release
      == Release(
        tag: "v9.9.9", assets: [.init(name: "x.tar.gz", url: "https://example.com/x.tar.gz")]))
  #expect(try Release.parse(#"{"tag_name": "v1.0.0"}"#).assets.isEmpty)
  #expect(throws: (any Error).self) {
    try Release.parse(#"{"tag_name": "v1.0.0", "assets": null}"#)
  }
  #expect(throws: (any Error).self) { try Release.parse(#"{"assets": []}"#) }
}

/// The asset name is agreed across the release workflow, the installer and
/// this updater with no compiler link between them.
@Test func bundleAssetNameMatchesReleaseWorkflowAndInstaller() throws {
  let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    .appending(path: "../../..").standardized.path
  let workflow = try String(
    contentsOfFile: root + "/.github/workflows/release.yml", encoding: .utf8)
  let installer = try String(contentsOfFile: root + "/install.sh", encoding: .utf8)
  let bundle = UpdateChannel.bundleAsset
  #expect(
    workflow.split(separator: "\n").contains {
      $0.contains("gh release create") && $0.contains(bundle)
    })
  #expect(installer.split(separator: "\n").contains { $0.contains("BUNDLE=\"\(bundle)\"") })
  #expect(installer.contains("download_bundle \"${TMPDIR}/${BUNDLE}\""))
  let fetch = try #require(
    installer.components(separatedBy: "download_bundle() {").dropFirst().first?
      .components(separatedBy: "\n}").first)
  #expect(
    fetch.contains("curl -fsSL") && !fetch.contains("-H") && !fetch.contains("--header")
      && !fetch.contains("$(") && !fetch.contains("GITHUB_TOKEN") && !fetch.contains("gh release"))
  #expect(installer.contains(#"--bundle "${TMPDIR}/${BUNDLE}""#))
  // Both installer verify paths carry the same signer pin as `coop update`.
  #expect(installer.contains("SIGNER_WORKFLOW=\"\(UpdateChannel.signerWorkflow)\""))
  #expect(
    installer.contains(
      #"--cert-identity "https://github.com/${REPO}/${SIGNER_WORKFLOW}@refs/tags/${VERSION}""#))
  let verifies = installer.split(separator: "\n").filter { $0.contains("gh attestation verify \"") }
  #expect(verifies.count == 2 && verifies.allSatisfy { $0.contains(#""${signer_pin[@]}""#) })
}

// MARK: - Sibling replacement

@Test func proxyReplacementIsANoOpWithoutAProxy() throws {
  let extract = try temporaryDirectory("extract")
  defer { try? FileManager.default.removeItem(atPath: extract) }
  try SelfReplace.replaceSiblingProxy(extract, currentExecutable: nil)
}

@Test func proxyReplacementSwapsTheSiblingAndDropsLegacyNames() throws {
  let extract = try temporaryDirectory("extract")
  let install = try temporaryDirectory("install")
  defer {
    try? FileManager.default.removeItem(atPath: extract)
    try? FileManager.default.removeItem(atPath: install)
  }
  try writeUpdateFile(extract + "/coop-proxy", "swift")
  try writeUpdateFile(install + "/coop", "coop-binary")
  for name in ["coop-proxy-swift", "coop-proxy-rs"] {
    try writeUpdateFile(install + "/" + name, "old")
  }
  try SelfReplace.replaceSiblingProxy(extract, currentExecutable: install + "/coop")
  #expect(readText(install + "/coop-proxy") == "swift")
  var status = stat()
  stat(install + "/coop-proxy", &status)
  #expect(status.st_mode & 0o777 == 0o755)
  #expect(!pathExists(install + "/coop-proxy-swift"))
  #expect(!pathExists(install + "/coop-proxy-rs"))
  #expect(readText(install + "/coop") == "coop-binary")
  // No staging or probe files are left behind.
  #expect(
    try FileManager.default.contentsOfDirectory(atPath: install).sorted() == ["coop", "coop-proxy"])
}

@Test func proxyReplacementFailsClosedWhenTheSiblingIsUnwritable() throws {
  let extract = try temporaryDirectory("extract")
  defer { try? FileManager.default.removeItem(atPath: extract) }
  try writeUpdateFile(extract + "/coop-proxy", "new-proxy")
  #expect(throws: (any Error).self) {
    try SelfReplace.replaceSiblingProxy(extract, currentExecutable: extract + "/no-such-dir/coop")
  }
}

@Test func obsoleteProxyArchiveIsRejectedBeforeReplacement() throws {
  let extract = try temporaryDirectory("extract")
  let install = try temporaryDirectory("install")
  defer {
    try? FileManager.default.removeItem(atPath: extract)
    try? FileManager.default.removeItem(atPath: install)
  }
  try writeUpdateFile(extract + "/coop-proxy-rs", "old-rust")
  try writeUpdateFile(extract + "/coop-proxy", "new-swift")
  try writeUpdateFile(extract + "/coop-sandbox", "runtime")
  try writeUpdateFile(install + "/coop-proxy", "old-swift")
  for replace in [SelfReplace.replaceSiblingProxy, SelfReplace.replaceSiblingRuntime] {
    #expect(throws: HostError("Release contains an obsolete proxy transition artifact")) {
      try replace(extract, install + "/coop")
    }
  }
  #expect(readText(install + "/coop-proxy") == "old-swift")
  #expect(!pathExists(install + "/coop-sandbox"))
}

@Test func runtimeReplacementRequiresBothCompanions() throws {
  let extract = try temporaryDirectory("extract")
  let install = try temporaryDirectory("install")
  defer {
    try? FileManager.default.removeItem(atPath: extract)
    try? FileManager.default.removeItem(atPath: install)
  }
  #expect(throws: HostError("Release is missing the coop-sandbox runtime")) {
    try SelfReplace.replaceSiblingRuntime(extract, currentExecutable: install + "/coop")
  }
  try writeUpdateFile(extract + "/coop-sandbox", "runtime")
  #expect(throws: HostError("Release is missing the coop-proxy companion")) {
    try SelfReplace.replaceSiblingRuntime(extract, currentExecutable: install + "/coop")
  }
  #expect(!pathExists(install + "/coop-sandbox"))
  try writeUpdateFile(extract + "/coop-proxy", "proxy")
  try SelfReplace.replaceSiblingRuntime(extract, currentExecutable: install + "/coop")
  #expect(readText(install + "/coop-sandbox") == "runtime")
}

@Test func unwritableInstallDirectoryIsReported() throws {
  let install = try temporaryDirectory("ro")
  defer {
    chmod(install, 0o755)
    try? FileManager.default.removeItem(atPath: install)
  }
  try writeUpdateFile(install + "/new", "x")
  chmod(install, 0o555)
  do {
    try SelfReplace.atomicReplace(install + "/new", over: install + "/coop")
    Issue.record("replaced into a read-only directory")
  } catch {
    #expect(
      "\(error)"
        == "Cannot write to \(install): Permission denied (os error 13).\nTry `sudo coop update` if coop is installed in a protected directory."
    )
  }
}

// MARK: - Background check state

@Test func updateStateRoundTripsInTheBaselineFormat() throws {
  let home = try temporaryDirectory("home")
  defer { try? FileManager.default.removeItem(atPath: home) }
  let path = try #require(UpdateCheck.statePath(home: home))
  #expect(path == home + "/Library/Application Support/coop/update-check.json")
  #expect(UpdateCheck.readState(home: home) == nil)
  try UpdateCheck.writeState(
    UpdateState(lastCheckedAt: 42, latestKnownVersion: "v1.2.3"), home: home)
  #expect(
    readText(path) == "{\n  \"last_checked_at\": 42,\n  \"latest_known_version\": \"v1.2.3\"\n}")
  var status = stat()
  stat(path, &status)
  #expect(status.st_mode & 0o777 == 0o644)
  #expect(
    UpdateCheck.readState(home: home)
      == UpdateState(lastCheckedAt: 42, latestKnownVersion: "v1.2.3"))
  try UpdateCheck.writeState(UpdateState(lastCheckedAt: 7), home: home)
  #expect(readText(path) == "{\n  \"last_checked_at\": 7,\n  \"latest_known_version\": null\n}")
  // Missing fields default; malformed content is no state.
  try writeUpdateFile(path, #"{"latest_known_version": "v9.9.9"}"#)
  #expect(
    UpdateCheck.readState(home: home) == UpdateState(lastCheckedAt: 0, latestKnownVersion: "v9.9.9")
  )
  for bad in [
    "{", "[]", #"{"last_checked_at": -1}"#, #"{"last_checked_at": "1"}"#,
    #"{"latest_known_version": 3}"#,
  ] {
    try writeUpdateFile(path, bad)
    #expect(UpdateCheck.readState(home: home) == nil, "\(bad)")
  }
}

@Test func removeStateLeavesASharedDirectory() throws {
  let home = try temporaryDirectory("home")
  defer { try? FileManager.default.removeItem(atPath: home) }
  let log = DiagnosticsLog()
  try UpdateCheck.removeState(home: home, diagnostics: log.diagnostics)
  let path = try #require(UpdateCheck.statePath(home: home))
  let directory = (path as NSString).deletingLastPathComponent
  try writeUpdateFile(path, "{}")
  try writeUpdateFile(directory + "/other", "keep")
  try UpdateCheck.removeState(home: home, diagnostics: log.diagnostics)
  #expect(!pathExists(path))
  #expect(pathExists(directory + "/other"))
  try FileManager.default.removeItem(atPath: directory + "/other")
  try writeUpdateFile(path, "{}")
  try UpdateCheck.removeState(home: home, diagnostics: log.diagnostics)
  #expect(!pathExists(directory))
}

@Test func checkIsDisabledByEverySource() {
  let dev = CoopBuild(version: "0.6.0", kind: .dev, versionString: "0.6.0-dev")
  #expect(UpdateCheck.disabled(build: dev, environment: [:], stdinIsTerminal: true))
  #expect(!UpdateCheck.disabled(build: releaseBuild, environment: [:], stdinIsTerminal: true))
  #expect(
    UpdateCheck.disabled(
      build: releaseBuild, environment: ["COOP_NO_UPDATE_CHECK": "1"], stdinIsTerminal: true))
  #expect(
    !UpdateCheck.disabled(
      build: releaseBuild, environment: ["COOP_NO_UPDATE_CHECK": "0"], stdinIsTerminal: true))
  #expect(
    UpdateCheck.disabled(build: releaseBuild, environment: ["CI": "true"], stdinIsTerminal: true))
  #expect(
    !UpdateCheck.disabled(build: releaseBuild, environment: ["CI": "1"], stdinIsTerminal: true))
  #expect(UpdateCheck.disabled(build: releaseBuild, environment: [:], stdinIsTerminal: false))
}

@Test func notifyAndIntervalRules() throws {
  let current = try SemanticVersion(parsing: "0.3.1")
  for (latest, due) in [
    ("0.3.2", true), ("1.0.0", true), ("0.3.1", false), ("0.3.0", false), ("0.4.0-rc.1", true),
  ] {
    #expect(
      UpdateCheck.notifyIsDue(current: current, latest: try SemanticVersion(parsing: latest)) == due
    )
  }
  #expect(UpdateCheck.intervalElapsed(now: 100_000, lastCheckedAt: 0, intervalHours: 24))
  #expect(!UpdateCheck.intervalElapsed(now: 100_000, lastCheckedAt: 99_999, intervalHours: 1))
  #expect(UpdateCheck.intervalElapsed(now: 103_600, lastCheckedAt: 100_000, intervalHours: 1))
  #expect(!UpdateCheck.intervalElapsed(now: 103_599, lastCheckedAt: 100_000, intervalHours: 1))
  #expect(!UpdateCheck.intervalElapsed(now: 0, lastCheckedAt: 100_000, intervalHours: 24))
  #expect(!UpdateCheck.intervalElapsed(now: 1, lastCheckedAt: 0, intervalHours: .max))
}

private func updateConfig(_ mode: UpdateMode, hours: UInt64 = 24) throws -> UpdateConfig {
  let text = #"{"updates": {"mode": "\#(mode.rawValue)", "check_interval_hours": \#(hours)}}"#
  return try ConfigLoader.decode(
    ConfigLoader.parse(Array(text.utf8), format: .jsonc, path: "c", limits: .configuration),
    path: "c", environment: .empty
  ).updates
}

@Test func startupNoticeReadsOnlyTheRecordedState() throws {
  let home = try temporaryDirectory("home")
  defer { try? FileManager.default.removeItem(atPath: home) }
  let log = DiagnosticsLog()
  let updater = Updater(
    environment: [:], home: home, build: releaseBuild, currentExecutable: nil,
    diagnostics: log.diagnostics)
  UpdateCheck.maybePrintNotify(try updateConfig(.notify), updater: updater, stdinIsTerminal: true)
  #expect(log.all.isEmpty)
  try UpdateCheck.writeState(
    UpdateState(lastCheckedAt: 1, latestKnownVersion: "v0.7.0"), home: home)
  UpdateCheck.maybePrintNotify(try updateConfig(.off), updater: updater, stdinIsTerminal: true)
  UpdateCheck.maybePrintNotify(try updateConfig(.notify), updater: updater, stdinIsTerminal: false)
  #expect(log.all.isEmpty)
  UpdateCheck.maybePrintNotify(try updateConfig(.notify), updater: updater, stdinIsTerminal: true)
  #expect(log.all == ["A newer coop (0.7.0) is available. Run `coop update` to install it."])
}

@Test func backgroundCheckStampsBeforeSpawningAndHonoursTheInterval() throws {
  let home = try temporaryDirectory("home")
  defer { try? FileManager.default.removeItem(atPath: home) }
  let updater = Updater(
    environment: ["PATH": home + "/empty-bin"], home: home, build: releaseBuild,
    currentExecutable: nil, diagnostics: DiagnosticsLog().diagnostics, now: { 1_000_000 })
  try UpdateCheck.writeState(
    UpdateState(lastCheckedAt: 999_000, latestKnownVersion: "v0.6.1"), home: home)
  var spawned: [@Sendable () -> Void] = []
  // Inside the interval: nothing happens.
  #expect(
    !UpdateCheck.maybeRunBackgroundCheck(
      try updateConfig(.notify, hours: 1), updater: updater, stdinIsTerminal: true
    ) { spawned.append($0) })
  #expect(
    !UpdateCheck.maybeRunBackgroundCheck(
      try updateConfig(.off, hours: 0), updater: updater, stdinIsTerminal: true
    ) { spawned.append($0) })
  #expect(spawned.isEmpty)
  // Elapsed: the stamp is written before the refresh runs, keeping the tag.
  #expect(
    UpdateCheck.maybeRunBackgroundCheck(
      try updateConfig(.notify, hours: 0), updater: updater, stdinIsTerminal: true
    ) { spawned.append($0) })
  #expect(spawned.count == 1)
  #expect(
    UpdateCheck.readState(home: home)
      == UpdateState(lastCheckedAt: 1_000_000, latestKnownVersion: "v0.6.1"))
  // The refresh fails (no curl on PATH) and leaves the state alone.
  spawned[0]()
  #expect(
    UpdateCheck.readState(home: home)
      == UpdateState(lastCheckedAt: 1_000_000, latestKnownVersion: "v0.6.1"))
}

// MARK: - End to end against stub tools

/// A release fixture served by a stub `curl` (and optionally a stub `gh`)
/// on a private PATH; the real network is never reached.
private struct UpdateFixture {
  let root: String
  var bin: String { root + "/bin" }
  var served: String { root + "/served" }
  var install: String { root + "/install" }
  var home: String { root + "/home" }
  var log: String { root + "/calls.log" }
  let tag = "v9.9.9"
  var directoryName: String { "coop-\(tag)-aarch64-apple-darwin" }
  var tarballName: String { directoryName + ".tar.gz" }

  static let curl = """
    #!/bin/sh
    printf 'curl' >>"$STUB_LOG"; for a in "$@"; do printf ' %s' "$a" >>"$STUB_LOG"; done; echo >>"$STUB_LOG"
    url=""; dest=""; stdin=0
    while [ $# -gt 0 ]; do
      case "$1" in
        -fsSL) ;;
        -H) shift; [ "$1" = "@-" ] && stdin=1 ;;
        -o) shift; dest="$1" ;;
        *) url="$1" ;;
      esac
      shift
    done
    [ "$stdin" = 1 ] && cat >>"$STUB_LOG.stdin"
    rest="${url#*://}"; rest="${rest#*/}"
    case "$rest" in repos/*) path="$FIXTURE/$rest" ;; *) path="$FIXTURE/${url##*/}" ;; esac
    [ -f "$path" ] || exit 22
    if [ -n "$dest" ]; then cp "$path" "$dest"; else cat "$path"; fi
    """

  static let gh = """
    #!/bin/sh
    printf 'gh' >>"$STUB_LOG"; for a in "$@"; do printf ' %s' "$a" >>"$STUB_LOG"; done; echo >>"$STUB_LOG"
    case "$1 $2" in
      "auth status") exit 1 ;;
      "attestation verify") exit "${GH_VERIFY_EXIT:-0}" ;;
    esac
    exit 2
    """

  init(withGh: Bool = false) throws {
    root = try temporaryDirectory("update")
    try writeUpdateFile(bin + "/curl", Self.curl, mode: 0o755)
    if withGh { try writeUpdateFile(bin + "/gh", Self.gh, mode: 0o755) }
    for (name, text) in [
      ("coop", "installed-coop"), ("coop-proxy", "installed-proxy"),
      ("coop-sandbox", "installed-runtime"),
    ] {
      try writeUpdateFile(install + "/" + name, text, mode: 0o755)
    }
    try FileManager.default.createDirectory(atPath: home, withIntermediateDirectories: true)
  }

  func remove() { try? FileManager.default.removeItem(atPath: root) }

  /// Pack `members` into the release archive and publish matching sums.
  func publish(
    _ members: [String: String], corruptSums: Bool = false, bundle: String? = nil,
    base: String = "http://fixture"
  ) throws {
    let stage = root + "/stage"
    try? FileManager.default.removeItem(atPath: stage)
    for (name, text) in members {
      try writeUpdateFile(stage + "/" + directoryName + "/" + name, text, mode: 0o755)
    }
    try FileManager.default.createDirectory(atPath: served, withIntermediateDirectories: true)
    let tar = Process()
    tar.executableURL = URL(fileURLWithPath: "/usr/bin/tar")
    tar.arguments = ["-czf", served + "/" + tarballName, "-C", stage, directoryName]
    tar.environment = ["COPYFILE_DISABLE": "1"]
    try tar.run()
    tar.waitUntilExit()
    let digest =
      corruptSums
      ? String(repeating: "a", count: 64)
      : Checksums.of(Array(try Data(contentsOf: URL(fileURLWithPath: served + "/" + tarballName))))
        .rawValue
    try writeUpdateFile(served + "/SHA256SUMS", "\(digest)  \(tarballName)\n")
    var assets = [
      #"{"name": "\#(tarballName)", "browser_download_url": "\#(base)/\#(tarballName)"}"#,
      #"{"name": "SHA256SUMS", "browser_download_url": "\#(base)/SHA256SUMS"}"#,
    ]
    if let bundle {
      try writeUpdateFile(served + "/attestations.jsonl", bundle)
      assets.append(
        #"{"name": "attestations.jsonl", "browser_download_url": "\#(base)/attestations.jsonl"}"#)
    }
    let json = #"{"tag_name": "\#(tag)", "assets": [\#(assets.joined(separator: ", "))]}"#
    try writeUpdateFile(served + "/repos/chr33s/coop/releases/latest", json)
    try writeUpdateFile(served + "/repos/chr33s/coop/releases/tags/\(tag)", json)
  }

  func updater(
    _ extra: [String: String] = ["COOP_UPDATE_API_BASE_URL": "http://fixture"], log: DiagnosticsLog,
    confirm: @escaping @Sendable (String) throws -> Bool = { _ in false }
  ) -> Updater {
    var environment = ["PATH": bin + ":/usr/bin:/bin", "FIXTURE": served, "STUB_LOG": self.log]
    environment.merge(extra) { $1 }
    return Updater(
      environment: environment, home: home, build: releaseBuild,
      currentExecutable: install + "/coop", diagnostics: log.diagnostics, confirm: confirm,
      now: { 1234 })
  }

  var installed: [String: String] {
    Dictionary(
      uniqueKeysWithValues: ((try? FileManager.default.contentsOfDirectory(atPath: install)) ?? [])
        .map {
          ($0, readText(install + "/" + $0) ?? "")
        })
  }

  var calls: [String] { (readText(log) ?? "").split(separator: "\n").map(String.init) }
}

private let fullRelease = [
  "coop": "new-coop", "coop-proxy": "new-proxy", "coop-sandbox": "new-runtime",
]
private let untouched = [
  "coop": "installed-coop", "coop-proxy": "installed-proxy", "coop-sandbox": "installed-runtime",
]

/// Serialized: these spawn many short-lived processes, and the process-wide
/// descriptor-leak check in HostTests tolerates only a little concurrency.
@Suite(.serialized) struct UpdateEndToEnd {
  @Test func updateReplacesAllThreeBinariesAndRecordsTheTag() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    try fixture.publish(fullRelease)
    let log = DiagnosticsLog()
    try fixture.updater(log: log).run(.init(skipConfirm: true))
    #expect(fixture.installed == fullRelease)
    #expect(
      UpdateCheck.readState(home: fixture.home)
        == UpdateState(lastCheckedAt: 1234, latestKnownVersion: "v9.9.9"))
    #expect(log.contains("attestation verification is DISABLED"))
    #expect(log.contains("Downloading coop-v9.9.9-aarch64-apple-darwin.tar.gz"))
    #expect(log.contains("coop updated to 9.9.9"))
    // Exact argv, in order; metadata then the two downloads.
    #expect(
      fixture.calls == [
        "curl -fsSL -H Accept: application/vnd.github+json http://fixture/repos/chr33s/coop/releases/latest",
        "curl -fsSL http://fixture/\(fixture.tarballName) -o " + fixture.calls[1].components(
          separatedBy: " -o "
        ).last!,
        "curl -fsSL http://fixture/SHA256SUMS -o " + fixture.calls[2].components(
          separatedBy: " -o "
        ).last!,
      ])
    #expect(fixture.calls[1].hasSuffix("/" + fixture.tarballName))
  }

  @Test func checksumMismatchLeavesEveryBinaryUntouched() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    try fixture.publish(fullRelease, corruptSums: true)
    do {
      try fixture.updater(log: DiagnosticsLog()).run(.init(skipConfirm: true))
      Issue.record("installed despite a checksum mismatch")
    } catch {
      #expect("\(error)".contains("SHA-256 mismatch"))
    }
    #expect(fixture.installed == untouched)
  }

  @Test func unlistedArchiveAndMissingSumsAreRefused() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    try fixture.publish(fullRelease)
    try writeUpdateFile(
      fixture.served + "/SHA256SUMS", "\(String(repeating: "a", count: 64))  other.tar.gz\n")
    #expect(throws: HostError("\(fixture.tarballName) not listed in SHA256SUMS")) {
      try fixture.updater(log: DiagnosticsLog()).run(.init(skipConfirm: true))
    }
    try writeUpdateFile(
      fixture.served + "/repos/chr33s/coop/releases/latest",
      #"{"tag_name": "v9.9.9", "assets": [{"name": "\#(fixture.tarballName)", "browser_download_url": "http://fixture/x"}]}"#
    )
    #expect(
      throws: HostError("Release has no SHA256SUMS asset; refusing to install unverified binary")
    ) {
      try fixture.updater(log: DiagnosticsLog()).run(.init(skipConfirm: true))
    }
    try writeUpdateFile(
      fixture.served + "/repos/chr33s/coop/releases/latest",
      #"{"tag_name": "v9.9.9", "assets": []}"#)
    #expect(
      throws: HostError(
        "Release v9.9.9 has no asset \(fixture.tarballName); this platform may not be supported by that release."
      )
    ) { try fixture.updater(log: DiagnosticsLog()).run(.init(skipConfirm: true)) }
    #expect(fixture.installed == untouched)
  }

  @Test func missingCompanionsAndObsoleteProxiesPreserveTheInstall() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    for (members, message) in [
      (["coop": "new", "coop-proxy": "p"], "Release is missing the coop-sandbox runtime"),
      (["coop": "new", "coop-sandbox": "r"], "Release is missing the coop-proxy companion"),
      (
        ["coop": "new", "coop-sandbox": "r", "coop-proxy-rs": "old"],
        "Release contains an obsolete proxy transition artifact"
      ),
      (["coop-proxy": "p", "coop-sandbox": "r"], "Extracted binary not found at"),
    ] {
      try fixture.publish(members)
      do {
        try fixture.updater(log: DiagnosticsLog()).run(.init(skipConfirm: true))
        Issue.record("installed \(members)")
      } catch {
        #expect("\(error)".contains(message))
      }
      #expect(fixture.installed == untouched)
    }
  }

  @Test func checkAndUpToDatePathsNeverDownload() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    try fixture.publish(fullRelease)
    let log = DiagnosticsLog()
    try fixture.updater(log: log).run(.init(checkOnly: true))
    #expect(log.contains("Update available: 0.6.0 -> 9.9.9"))
    try writeUpdateFile(
      fixture.served + "/repos/chr33s/coop/releases/latest",
      #"{"tag_name": "v0.6.0", "assets": []}"#)
    try fixture.updater(log: log).run(.init(checkOnly: true))
    #expect(log.contains("Up to date: coop 0.6.0"))
    try fixture.updater(log: log).run(.init(skipConfirm: true))
    #expect(log.contains("Already on latest: coop 0.6.0"))
    // Declining the prompt downloads nothing.
    try fixture.publish(fullRelease)
    let asked = Mutex<[String]>([])
    try fixture.updater(log: log) { prompt in
      asked.withLock { $0.append(prompt) }
      return false
    }.run(.init())
    #expect(asked.withLock { $0 } == ["Update coop from 0.6.0 to 9.9.9?"])
    #expect(log.contains("Update cancelled"))
    #expect(fixture.calls.allSatisfy { !$0.contains(" -o ") })
    #expect(fixture.installed == untouched)
    #expect(UpdateCheck.readState(home: fixture.home) == nil)
  }

  @Test func pinnedVersionFetchesThatTagAndInstallsEvenIfNotNewer() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    try fixture.publish(fullRelease)
    try fixture.updater(log: DiagnosticsLog()).run(.init(pinnedVersion: "9.9.9", skipConfirm: true))
    #expect(fixture.calls.first?.hasSuffix("/repos/chr33s/coop/releases/tags/v9.9.9") == true)
    #expect(fixture.installed == fullRelease)
    #expect(throws: (any Error).self) {
      try fixture.updater(log: DiagnosticsLog()).run(
        .init(pinnedVersion: "../x", skipConfirm: true))
    }
  }

  @Test func devBuildsAreRefusedBeforeAnyRequest() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    let updater = Updater(
      environment: ["PATH": fixture.bin], home: fixture.home,
      build: CoopBuild(version: "0.6.0", kind: .dev, versionString: "0.6.0-dev (swift host)"),
      currentExecutable: fixture.install + "/coop", diagnostics: DiagnosticsLog().diagnostics)
    #expect(
      throws: HostError(
        "This is a dev build (0.6.0-dev (swift host)); `coop update` only replaces release binaries.\nRe-run install.sh (or build from source) to replace a dev build."
      )
    ) { try updater.run(.init(skipConfirm: true)) }
    #expect(fixture.calls.isEmpty)
  }

  @Test func bearerTokenTravelsOnStdinOnly() throws {
    let fixture = try UpdateFixture()
    defer { fixture.remove() }
    try fixture.publish(
      fullRelease, base: "https://github.com/chr33s/coop/releases/download/v9.9.9")
    let log = DiagnosticsLog()
    // No gh: checksum-only verification, with the note on stderr.
    try fixture.updater(["GITHUB_TOKEN": "ghp_secret"], log: log).run(.init(skipConfirm: true))
    #expect(fixture.installed == fullRelease)
    #expect(fixture.calls.allSatisfy { !$0.contains("ghp_secret") && $0.contains(" -H @- ") })
    #expect(fixture.calls[0].hasSuffix(" https://api.github.com/repos/chr33s/coop/releases/latest"))
    #expect(
      readText(fixture.log + ".stdin")
        == String(repeating: "Authorization: token ghp_secret\n", count: 3))
    #expect(
      log.contains("Note: `gh` not installed — skipped cryptographic attestation verification."))
  }

  @Test func attestationUsesTheBundleWithoutCredentialsAndFailsClosed() throws {
    let fixture = try UpdateFixture(withGh: true)
    defer { fixture.remove() }
    try fixture.publish(fullRelease, bundle: #"{"bundle": 1}"#, base: "https://github.com/dl")
    let failing = fixture.updater(
      ["GITHUB_TOKEN": "ghp_secret", "GH_VERIFY_EXIT": "1"], log: DiagnosticsLog())
    do {
      try failing.run(.init(skipConfirm: true))
      Issue.record("installed despite a failed attestation")
    } catch {
      #expect("\(error)".contains("Attestation verification failed for "))
      #expect("\(error)".contains("— refusing to install\n"))
    }
    #expect(fixture.installed == untouched)
    let verify = try #require(fixture.calls.first { $0.hasPrefix("gh attestation verify") })
    #expect(
      verify.contains(
        " --repo chr33s/coop --cert-identity https://github.com/chr33s/coop/.github/workflows/release.yml@refs/tags/v9.9.9 --source-ref refs/tags/v9.9.9 --deny-self-hosted-runners --bundle "
      ))
    #expect(verify.hasSuffix("/attestations.jsonl"))
    // The bundle is fetched with a bare curl: no header, no token on stdin.
    let bundleFetch = try #require(fixture.calls.first { $0.contains("attestations.jsonl -o") })
    #expect(bundleFetch.hasPrefix("curl -fsSL https://github.com/dl/attestations.jsonl -o "))
    #expect(
      readText(fixture.log + ".stdin")?.components(separatedBy: "\n").filter { !$0.isEmpty }.count
        == 3)

    try fixture.updater(["GITHUB_TOKEN": "ghp_secret"], log: DiagnosticsLog()).run(
      .init(skipConfirm: true))
    #expect(fixture.installed == fullRelease)
  }

  @Test func attestationFallsBackToTheAPIAndNamesWhy() throws {
    let fixture = try UpdateFixture(withGh: true)
    defer { fixture.remove() }
    try fixture.publish(fullRelease, bundle: "", base: "https://github.com/dl")
    let log = DiagnosticsLog()
    do {
      try fixture.updater(["GH_VERIFY_EXIT": "1"], log: log).run(.init(skipConfirm: true))
      Issue.record("installed despite a failed attestation")
    } catch {
      #expect(
        "\(error)".contains(
          "verified through the GitHub API because the published attestations.jsonl is empty"))
    }
    #expect(log.contains("attestations.jsonl for release v9.9.9 is empty"))
    let verify = try #require(fixture.calls.first { $0.hasPrefix("gh attestation verify") })
    #expect(!verify.contains("--bundle"))
    #expect(fixture.installed == untouched)
  }
}
