// Generated by scripts/generate-embedded-resources.py; do not edit.

/// Guest scripts embedded in the binary, keyed by their path under
/// `scripts/guest/`.
public enum EmbeddedResources {
  public static let guestScripts: [String: String] = [
    "claude-code.sh": #"""
    set -euo pipefail

    # GUEST_USER is exported by the image build (ImageBuild.swift).
    : "${GUEST_USER:?GUEST_USER must be set by the orchestrator}"

    # Skip if a profile already provided a claude binary (e.g. stub-claude
    # for testing). Profile post_install scripts run before this script.
    # Using if/else (not early `exit 0`) because this file is concatenated
    # with codex.sh into a single shell invocation; an unconditional exit
    # would skip the codex installer too.
    if [ -x "/home/${GUEST_USER}/.local/bin/claude" ]; then
        echo '  [guest] Claude Code CLI already installed, skipping.'
    else
        echo '  [guest] Installing Claude Code CLI...'

        # Download the installer to a file first. The `curl | bash` pattern causes
        # the installer's `install` subcommand to inherit curl's pipe as stdin,
        # hanging on interactive prompts in non-interactive contexts (cloud-init,
        # chroot). Running from a file with stdin from /dev/null avoids this.
        INSTALLER=$(mktemp)
        chmod 644 "$INSTALLER"
        trap 'rm -f "$INSTALLER"' EXIT

        # Retry with exponential backoff — transient network errors are common
        # during cloud-init (DNS not ready, CDN hiccups, etc.).
        # Uses `if` to suppress set -e for the curl command.
        MAX_RETRIES=4
        RETRY_DELAY=5
        for attempt in $(seq 1 "$MAX_RETRIES"); do
            if curl -fsSL -o "$INSTALLER" https://claude.ai/install.sh 2>/tmp/claude-curl-err; then
                break
            fi
            CURL_EXIT=$?
            CURL_ERR=$(cat /tmp/claude-curl-err 2>/dev/null || true)
            if [ "$attempt" -eq "$MAX_RETRIES" ]; then
                echo "  [guest] ERROR: Failed to download Claude Code installer" \
                     "after $MAX_RETRIES attempts." >&2
                echo "  [guest] curl exit code: $CURL_EXIT" >&2
                echo "  [guest] curl error: ${CURL_ERR:-none}" >&2
                exit 1
            fi
            echo "  [guest] Download failed (attempt $attempt/$MAX_RETRIES," \
                 "curl exit $CURL_EXIT), retrying in ${RETRY_DELAY}s..."
            sleep "$RETRY_DELAY"
            RETRY_DELAY=$((RETRY_DELAY * 2))
        done

        su - "${GUEST_USER}" -c "bash '$INSTALLER'" </dev/null
    fi

    """#,
    "codex-account.sh": #"""
    # shellcheck shell=bash
    set -euo pipefail

    echo '  [guest] Installing codex-account shortcut...'
    cat >/usr/local/bin/codex-account <<'CODEXACCOUNTEOF'
    #!/usr/bin/env bash
    set -euo pipefail

    CODEX_BIN="/usr/local/bin/codex"
    CODEX_CONFIG="${CODEX_HOME:-$HOME/.codex}/config.toml"
    KEYRING_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/keyrings"
    PROBE_SERVICE="coop-codex"
    PROBE_ACCOUNT="keyring-probe"

    die() {
        echo "codex-account: $*" >&2
        exit 1
    }

    # coop writes `cli_auth_credentials_store = "keyring"` into the guest Codex
    # config only under `[codex] auth = "chatgpt"`. Every other mode reads
    # credentials from auth.json, where the D-Bus/keyring session is pure overhead
    # (and its password prompt is an outright regression). Gating on the config the
    # guest actually has lets every Codex entry point route through this wrapper.
    keyring_mode_in() {
        local config=$1
        local first_line=""
        [ -r "$config" ] \
            && IFS= read -r first_line < "$config" \
            && [ "$first_line" = 'cli_auth_credentials_store = "keyring"' ]
    }

    keyring_mode() {
        keyring_mode_in "$CODEX_CONFIG"
    }

    keyring_exists() {
        compgen -G "$KEYRING_DIR/*.keyring" >/dev/null 2>&1
    }

    # secret-tool's stderr from the last probe, so the failure path can report the
    # real cause instead of only guessing at the password.
    PROBE_ERROR=""

    # Writing proves the collection is both reachable and unlocked; a lookup can
    # succeed against a locked collection. The probe item is cleared again so
    # repeated launches do not accumulate junk in the user's keyring.
    probe_keyring() {
        PROBE_ERROR="$(printf 'ok' \
            | timeout 5 secret-tool store \
                --label="coop Codex keyring probe" \
                service "$PROBE_SERVICE" \
                account "$PROBE_ACCOUNT" \
                2>&1 >/dev/null)" || return 1
        timeout 5 secret-tool clear \
            service "$PROBE_SERVICE" \
            account "$PROBE_ACCOUNT" \
            >/dev/null 2>&1 || true
    }

    unlock_keyring() {
        local creating=0 password confirm output
        keyring_exists || creating=1

        if [ ! -t 0 ]; then
            die "Codex ChatGPT auth needs an interactive TTY to unlock the guest keyring"
        fi

        # On a fresh guest there is no keyring yet, so this prompt is choosing a
        # password rather than entering one. Say so, and confirm it — an
        # unnoticed typo would otherwise lock the credentials behind a password
        # the user cannot reproduce on the next launch.
        if [ "$creating" = 1 ]; then
            printf '%s\n' \
                'codex-account: this VM has no guest keyring yet.' \
                'Choose a password to create one. It encrypts the Codex account' \
                'credentials stored inside the guest, and later `coop codex` runs' \
                'ask for it again. It is not your ChatGPT or host password.' >&2
        fi

        if ! IFS= read -rsp "Codex keyring password: " password; then
            echo >&2
            die "failed to read keyring password"
        fi
        echo >&2

        if [ -z "$password" ]; then
            die "keyring password must not be empty"
        fi

        if [ "$creating" = 1 ]; then
            if ! IFS= read -rsp "Confirm keyring password: " confirm; then
                echo >&2
                die "failed to read keyring password"
            fi
            echo >&2
            if [ "$password" != "$confirm" ]; then
                die "passwords did not match; no keyring was created"
            fi
        fi

        # Let the daemon's stderr reach the terminal. Once it forks it redirects
        # its own fd 2, so this surfaces only its startup diagnostics — the probe
        # below is what reports a wrong password.
        output="$(printf '%s' "$password" \
            | timeout 30 gnome-keyring-daemon --unlock --components=secrets)" \
            || die "failed to unlock the guest keyring"

        # The daemon prints its session env as `NAME=value` lines. Take only
        # those, and export them: an unfiltered `eval` would execute any GLib
        # diagnostic the daemon puts on stdout as a command, and a bare
        # assignment would not reach Codex anyway.
        while IFS= read -r line; do
            case "$line" in
                [A-Za-z_]*=*) export "${line%%=*}=${line#*=}" ;;
            esac
        done <<<"$output"
    }

    if [ ! -x "$CODEX_BIN" ]; then
        die "$CODEX_BIN is missing; rebuild the coop image"
    fi

    # coop stages and maintains Codex state only in ~/.codex. In ChatGPT account
    # mode, an explicit CODEX_HOME could put auth.json outside coop's cleanup path
    # (including under /workspace, which is pulled back to the host). Refuse the
    # unsupported override before inspecting its config. coop writes the managed
    # credential-store key as the first line, so a same-named nested key cannot
    # trigger this guard.
    if [ -n "${CODEX_HOME:-}" ] \
        && keyring_mode_in "$HOME/.codex/config.toml"; then
        die "CODEX_HOME is set, but coop manages ~/.codex and it selects the keyring credential store; unset CODEX_HOME for Codex ChatGPT account auth"
    fi

    if ! keyring_mode; then
        exec "$CODEX_BIN" "$@"
    fi

    # The keyring speaks D-Bus, and a headless SSH session has no session bus.
    # Re-exec under one, using the env guard to avoid recursing forever.
    if [ "${COOP_CODEX_ACCOUNT_DBUS:-0}" != "1" ]; then
        command -v dbus-run-session >/dev/null 2>&1 \
            || die "dbus-run-session is missing; install dbus-user-session or rebuild the coop image"
        export COOP_CODEX_ACCOUNT_DBUS=1
        exec dbus-run-session -- "$0" "$@"
    fi

    for tool in gnome-keyring-daemon secret-tool timeout; do
        command -v "$tool" >/dev/null 2>&1 \
            || die "$tool is missing; rebuild the coop image with Codex account-auth support"
    done

    # A nested codex-account — an in-guest agent shelling out to `codex-account` or
    # `codex-yolo` — inherits this bus and its already-unlocked keyring. Unlocking
    # again there would fail, for the same reason the ordering below matters, so
    # reuse the session instead of prompting a second time.
    if [ "${COOP_CODEX_ACCOUNT_UNLOCKED:-0}" = "1" ]; then
        probe_keyring \
            || die "inherited guest Secret Service session is unusable${PROBE_ERROR:+: $PROBE_ERROR}"
    else
        # Unlock before anything else touches the bus. `gnome-keyring-daemon
        # --unlock` only creates and unlocks the login collection when it is the
        # process that starts the daemon; once any daemon owns
        # `org.freedesktop.secrets` it hands the unlock to the graphical
        # gcr-prompter, which cannot render on a headless guest and exits
        # immediately. That includes a daemon the probe itself would D-Bus-activate,
        # so there is no cheap "is it already unlocked?" check to make first.
        unlock_keyring
        probe_keyring \
            || die "guest Secret Service is unavailable${PROBE_ERROR:+: $PROBE_ERROR}; check the keyring password"
        export COOP_CODEX_ACCOUNT_UNLOCKED=1
    fi

    # Codex 0.154.0 can reuse a desktop daemon on another D-Bus session when
    # there are no explicit config overrides. Keep terminal auth on the keyring
    # we just unlocked. Prepend the default so caller overrides retain precedence.
    exec "$CODEX_BIN" -c 'cli_auth_credentials_store="keyring"' "$@"
    CODEXACCOUNTEOF
    chmod 755 /usr/local/bin/codex-account

    """#,
    "codex.sh": #"""
    # Keep the installer cleanup local when provisioning snippets are concatenated.
    (
        set -euo pipefail
        : "${GUEST_USER:?GUEST_USER must be set by the orchestrator}"

        # Profiles may supply their own Codex; explicit updates replace it.
        if [ -z "${COOP_FORCE_INSTALL:-}" ] && [ -x /usr/local/bin/codex ]; then
            echo '  [guest] Codex CLI already installed, skipping.'
            exit 0
        fi

        echo '  [guest] Installing Codex CLI with the native installer...'
        CODEX_NATIVE_BIN="/home/${GUEST_USER}/.local/bin/codex"
        CODEX_INSTALLER=$(mktemp)
        CODEX_LINK_TMP="/usr/local/bin/codex.new.$$"
        trap 'rm -f "$CODEX_INSTALLER" "$CODEX_LINK_TMP"' EXIT
        chmod 0644 "$CODEX_INSTALLER"

        # curl retries transient failures without running a partially downloaded script.
        curl -fsSL --retry 3 --retry-all-errors \
            -o "$CODEX_INSTALLER" https://chatgpt.com/codex/install.sh

        # Retain the upstream package layout and guest ownership for `codex update`.
        # PATH is already managed by coop; the installer need not edit shell profiles.
        su - "$GUEST_USER" -c \
            "PATH='/home/${GUEST_USER}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' CODEX_NON_INTERACTIVE=1 sh '$CODEX_INSTALLER'" \
            </dev/null

        # Keep existing coop wrappers and absolute-path callers working after updates.
        ln -s "$CODEX_NATIVE_BIN" "$CODEX_LINK_TMP"
        mv -Tf "$CODEX_LINK_TMP" /usr/local/bin/codex

        # The native installer validates its package; verify coop's link as its user.
        if ! su - "$GUEST_USER" -c '/usr/local/bin/codex --version' </dev/null; then
            echo '  [guest] ERROR: Codex is not usable through /usr/local/bin/codex' >&2
            exit 1
        fi
    )

    """#,
    "docker-repo.sh": #"""
    set -euo pipefail

    echo '  [guest] Adding Docker CE repository...'
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list

    """#,
    "gh-cli-repo.sh": #"""
    set -euo pipefail

    echo '  [guest] Adding GitHub CLI repository...'
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null
    chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] \
        https://cli.github.com/packages stable main" \
        > /etc/apt/sources.list.d/github-cli.list

    """#,
    "profiles/node-pre.sh": #"""
    set -euo pipefail

    echo '  [guest] Adding NodeSource 22.x repository...'
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -

    """#,
    "profiles/rust-post.sh": #"""
    set -euo pipefail

    echo '  [guest] Installing Rust via rustup...'
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    cp /root/.cargo/bin/* /usr/local/bin/ 2>/dev/null || true

    """#,
  ]

  public static func guestScript(_ path: String) -> String { guestScripts[path]! }
}
