#!/usr/bin/env python3
"""Regenerate Sources/CoopHost/EmbeddedResources.swift from scripts/guest/.

The Swift host embeds guest scripts in the binary, as the Rust host did with
`include_str!`. `EmbeddedResourcesTests` fails when this file is stale.

    python3 scripts/generate-embedded-resources.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = sorted(p for p in (ROOT / "scripts" / "guest").rglob("*") if p.is_file())
OUT = ROOT / "Sources" / "CoopHost" / "EmbeddedResources.swift"


def literal(text):
    hashes = "#"
    # Grow the delimiter until neither a closing quote nor an escape or
    # interpolation (`\#(`) with it can occur in the text.
    while f'"{hashes}' in text or f"\\{hashes}" in text:
        hashes += "#"
    # A multi-line literal drops the newline before its closing delimiter,
    # so add one to keep the file's final newline.
    return f'{hashes}"""\n{text}\n"""{hashes}'


def main():
    lines = [
        "// Generated by scripts/generate-embedded-resources.py; do not edit.",
        "",
        "/// Guest scripts embedded in the binary, keyed by their path under",
        "/// `scripts/guest/`.",
        "public enum EmbeddedResources {",
        "  public static let guestScripts: [String: String] = [",
    ]
    for path in SOURCES:
        key = path.relative_to(ROOT / "scripts" / "guest").as_posix()
        text = path.read_text(encoding="utf-8")
        lines.append(f'    "{key}": {literal(text)},')
    lines += ["  ]", "", "  public static func guestScript(_ path: String) -> String { guestScripts[path]! }", "}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(SOURCES)} scripts)")


if __name__ == "__main__":
    main()
