#!/usr/bin/env python3
"""Regenerate Sources/IsoHost/EmbeddedResources.swift from scripts/guest/,
and EmbeddedManagedBackend.swift from the managed-backend launcher and profile.

The Swift host embeds these files in the binary so it needs no resource files
at run time. `EmbeddedResourcesTests` and `InferenceHardeningTests` fail when
the generated files are stale.

    python3 scripts/generate-embedded-resources.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = sorted(p for p in (ROOT / "scripts" / "guest").rglob("*") if p.is_file())
OUT = ROOT / "Sources" / "IsoHost" / "EmbeddedResources.swift"
HOST = ROOT / "Sources" / "IsoHost"
MANAGED_OUT = HOST / "EmbeddedManagedBackend.swift"


def literal(text):
    hashes = "#"
    # Grow the delimiter until neither a closing quote nor an escape or
    # interpolation (`\#(`) with it can occur in the text.
    while f'"{hashes}' in text or f"\\{hashes}" in text:
        hashes += "#"
    # A multi-line literal drops the newline before its closing delimiter,
    # so add one to keep the file's final newline. Swift strips the closing
    # delimiter's indentation from every line, so indent the body to match
    # `swift format` (blank lines stay empty).
    body = "\n".join(f"    {line}" if line else "" for line in text.split("\n"))
    return f'{hashes}"""\n{body}\n    """{hashes}'


def main():
    lines = [
        "// Generated by scripts/generate-embedded-resources.py; do not edit.",
        "",
        "/// Guest scripts embedded in the binary, keyed by their path under",
        "/// `scripts/guest/`.",
        "public enum EmbeddedResources {",
        "  public static let guestScripts: [String: String] = [",
    ]
    for path in SOURCES:
        key = path.relative_to(ROOT / "scripts" / "guest").as_posix()
        text = path.read_text(encoding="utf-8")
        lines.append(f'    "{key}": {literal(text)},')
    lines += ["  ]", "", "  public static func guestScript(_ path: String) -> String { guestScripts[path]! }", "}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(SOURCES)} scripts)")
    managed = [
        "// Generated by scripts/generate-embedded-resources.py; do not edit.",
        "",
        "/// `inference-launcher.py` and `seatbelt-inference-backend.sb`, installed by",
        "/// `iso inference provision` (spec §20.3–20.4).",
        "enum EmbeddedManagedBackend {",
        f"  static let launcher = {literal((HOST / 'inference-launcher.py').read_text(encoding='utf-8'))}",
        "",
        f"  static let profile = {literal((HOST / 'seatbelt-inference-backend.sb').read_text(encoding='utf-8'))}",
        "}",
        "",
    ]
    MANAGED_OUT.write_text("\n".join(managed), encoding="utf-8")
    print(f"wrote {MANAGED_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
