#!/usr/bin/env python3
"""Show that critical Swift host tests fail when their protected behavior is
removed. See docs/testing.md for required mutation coverage.

Each fault edits one production source line in a scratch copy of the package,
runs the named test filter there, and requires at least one failure. The
working tree is never modified. Exit status is non-zero if any fault survives.
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (id, file, original text, replacement, swift test filter)
FAULTS = [
    ("ordered-json-depth", "Sources/IsoHost/Support/OrderedJSON.swift",
     "guard depth < OrderedJSON.maxDepth else", "guard depth >= 0 else",
     "orderedJSONPreservesDocumentOrderAndBounds"),
    ("ordered-json-trailing", "Sources/IsoHost/Support/OrderedJSON.swift",
     "guard parser.index == bytes.count else", "guard true else",
     "orderedJSONPreservesDocumentOrderAndBounds"),
    ("guest-exec-delete", "iso-sandbox/Sources/IsoSandboxCore/GuestProcess.swift",
     "      try? await process.delete()", "      _ = process",
     "guestExecDeletesBeforeReturningWithoutKillingAnExitedProcess"),
    ("guest-exec-kill", "iso-sandbox/Sources/IsoSandboxCore/GuestProcess.swift",
     "if !exited { try? await process.kill(.kill) }", "_ = exited",
     "guestExecKillsOnTimeoutAndPreservesTheWaitError"),
    ("guest-exec-shield", "iso-sandbox/Sources/IsoSandboxCore/GuestProcess.swift",
     "await withTaskCancellationShield {", "do {",
     "guestExecShieldsCleanupAfterCancellation"),
    ("guest-exec-exited", "iso-sandbox/Sources/IsoSandboxCore/GuestProcess.swift",
     "if !exited { try? await process.kill(.kill) }", "if true { try? await process.kill(.kill) }",
     "guestExecDeletesBeforeReturningWithoutKillingAnExitedProcess"),
    ("guest-output-cap", "iso-sandbox/Sources/IsoSandboxCore/Owner.swift",
     "$0.append(data.prefix(max(0, Self.limit - $0.count)))", "$0.append(data)",
     "guestOutputIsCapped|concurrentGuestOutputRemainsCapped"),
    ("file-lock-release", "Sources/IsoCore/FileLock.swift",
     "      descriptor = nil\n      close(fd)", "      descriptor = nil\n      _ = fd",
     "concurrentFileLockReleaseUnlocksWithoutClosingOtherDescriptors"),
    ("file-lock-release-once", "Sources/IsoCore/FileLock.swift",
     "      descriptor = nil\n      close(fd)", "      _ = descriptor\n      close(fd)",
     "concurrentFileLockReleaseUnlocksWithoutClosingOtherDescriptors"),
    ("secret-resolver-sharing", "Sources/IsoCLI/Commands/SecretsCommands.swift",
     "      instances[store.directory] = created", "      _ = created",
     "concurrentSecretResolversShareOneStoreCache"),
    ("passphrase-cache", "Sources/IsoCLI/Commands/SecretsCommands.swift",
     "      cached = passphrase", "      cached = nil",
     "concurrentPassphraseReadsShareOneDescriptorRead"),
    ("machine-passphrase-prompt", "Sources/IsoCLI/Commands/SecretsCommands.swift",
     "    if !interactive {", "    if false {",
     "machineModeNeverPromptsForThePassphrase"),
    ("machine-error-chain", "Sources/IsoCLI/Support/MachineErrors.swift",
     "      next = current.contextError?.cause", "      next = nil",
     "errorsClassifyAlongTheContextChain"),
    ("machine-error-sanitize", "Sources/IsoCLI/Support/MachineErrors.swift",
     "self.message = Self.bounded(neutralizeControls(message))", "self.message = message",
     "errorMessagesAreSanitizedAndBounded"),
    ("machine-error-details-sanitize", "Sources/IsoCLI/Support/MachineErrors.swift",
     "path: neutralizeControls(path), acceptedFlags: flags.map(neutralizeControls))",
     "path: path, acceptedFlags: flags)",
     "errorMessagesAreSanitizedAndBounded"),
    ("scanner-strings", "Sources/IsoConfiguration/JSONCScanner.swift",
     "if byte == quote { state = .string }", "_ = quote",
     "commentMarkersInsideStringsAreData"),
    ("scanner-unterminated", "Sources/IsoConfiguration/JSONCScanner.swift",
     "&& policy == .configuration {", "&& policy == .devcontainer {",
     "unterminatedBlockCommentIsRejectedForConfiguration"),
    ("preflight-duplicates", "Sources/IsoConfiguration/JSONPreflight.swift",
     "guard objectKeys[objectKeys.count - 1].insert(key).inserted else {",
     "guard objectKeys[objectKeys.count - 1].insert(key).inserted || true else {",
     "duplicateKeysAreDetectedAfterDecoding"),
    ("preflight-trailing-comma", "Sources/IsoConfiguration/JSONPreflight.swift",
     "guard current == UInt8(ascii: \"\\\"\") else { throw fail(.syntax(\"expected an object key\")) }",
     "if current == UInt8(ascii: \"}\") { return }",
     "rejectsJSON5AndTrailingCommas"),
    ("preflight-depth", "Sources/IsoConfiguration/JSONPreflight.swift",
     "guard stack.count < limits.maxDepth else", "guard stack.count >= 0 else",
     "resourceLimitsAreEnforcedBeforeDecoding"),
    ("fractional-integers", "Sources/IsoConfiguration/JSONValue.swift",
     "if !fractional.contains(components) {", "if true {",
     "fractionalLiteralsDoNotSatisfyIntegerFields"),
    ("literal-credentials", "Sources/IsoConfiguration/IsoConfig.swift",
     "guard value.hasPrefix(\"cmd:\") || value.hasPrefix(\"vault:\") else { return nil }", "",
     "proxyCredentialsMustBeCommandReferences"),
    ("missing-explicit-config", "Sources/IsoConfiguration/ConfigLoader.swift",
     "throw .missingFile(path: path)",
     'return try decode(.object([:]), path: path, environment: environment)',
     "missingSelectedConfigurationFailsButImplicitAbsenceUsesDefaults"),
    ("root-config-strict", "Sources/IsoConfiguration/ConfigDecoding.swift",
     '"workspace", "egress", "egress_filter", "limits", "security",',
     '"workspace", "egress", "egress_filter", "limits", "security", "egres",',
     "unknownRootAndVMFieldsAreRejected"),
    ("vm-config-strict", "Sources/IsoConfiguration/ConfigDecoding.swift",
     'try r.rejectUnknown(allowing: ["vcpu_count", "mem_size_mib", "template_size_gib"])', "",
     "unknownRootAndVMFieldsAreRejected"),
    ("apple-container-strict", "Sources/IsoConfiguration/ConfigDecoding.swift",
     "try r.rejectUnknown(allowing: appleContainerKeys)", "",
     "unknownKeysFollowPerSectionPolicy"),
    ("null-defaulted", "Sources/IsoConfiguration/ConfigDecoding.swift",
     "guard let value = members[key] else { return try fallback() }",
     "guard let value = members[key], value != .null else { return try fallback() }",
     "nullIsAbsentOnlyForOptionalFields"),
    ("spawn-cloexec", "Sources/IsoHost/Processes/ProcessRunner.swift",
     "(ownGroup ? POSIX_SPAWN_SETPGROUP : 0) | POSIX_SPAWN_CLOEXEC_DEFAULT",
     "(ownGroup ? POSIX_SPAWN_SETPGROUP : 0)",
     "childSeesOnlyTheExplicitEnvironmentAndNoExtraDescriptors"),
    ("spawn-process-group", "Sources/IsoHost/Processes/ProcessRunner.swift",
     "    if ownsGroup { kill(-pid, SIGKILL) }\n", "",
     "deadlineKillsTheWholeProcessGroup"),
    ("mode-widening", "Sources/IsoCore/AtomicFile.swift",
     "existing.st_mode & 0o777 & mode : mode", "mode : mode",
     "atomicWriteNeverWidensAnExistingMode"),
    ("gate-agent-forwarding", "Sources/IsoHost/Runtime/IsolationGate.swift",
     "guard !effective.sshAgentForwarding else {", "guard true else {",
     "gateRejectsEachExposureNetworkAndIdentityChange"),
    ("gate-network", "Sources/IsoHost/Runtime/IsolationGate.swift",
     "guard address == ip, subnetOK else {", "guard address == ip else {",
     "gateRejectsEachExposureNetworkAndIdentityChange"),
    ("gate-record-owner", "Sources/IsoHost/Runtime/IsolationGate.swift",
     "guard record.id == expected.sandbox.rawValue, record.owner == expected.owner.rawValue else {",
     "guard record.id == expected.sandbox.rawValue else {",
     "gateRejectsEachExposureNetworkAndIdentityChange"),
    ("runtime-env", "Sources/IsoHost/Runtime/SandboxRuntime.swift",
     "var out = parent.filter { inheritedVariables.contains($0.key) }", "var out = parent",
     "realExecutorSanitizesEnvironmentAndBoundsOutput"),
    ("control-file-nofollow", "Sources/IsoHost/State/StateStore.swift",
     "let fd = open(path, O_RDONLY | O_CLOEXEC | O_NOFOLLOW)", "let fd = open(path, O_RDONLY | O_CLOEXEC)",
     "controlFilesDoNotFollowSymlinks"),
    ("sidecar-owner", "Sources/IsoHost/State/StateStore.swift",
     "guard ownerID == owner.id, machineID.belongs(to: owner.id) else {",
     "guard machineID.belongs(to: ownerID) else {",
     "foreignAndUnknownSchemasAreRefused"),
    ("host-key-pin", "Sources/IsoHost/Guest/SSH.swift",
     "guard FileManager.default.fileExists(atPath: knownHosts) else {", "guard true else {",
     "pinnedTargetRequiresAnEnrolledKeyAndSafePaths"),
    ("host-key-pin-equality", "Sources/IsoHost/Guest/HostKeys.swift",
     "guard data == Data(line.utf8) else {", "guard !data.isEmpty else {",
     "enrollOnceThenThePinIsEnforced"),
    ("host-key-no-reenroll", "Sources/IsoHost/Guest/HostKeys.swift",
     "      if lstat(path, &status) == 0 {\n", "      if false {\n",
     "enrollOnceThenThePinIsEnforced"),
    ("destroy-owner-check", "Sources/IsoHost/Lifecycle/AppleLifecycle.swift",
     "guard ownerID == owner.id, machine.belongs(to: owner.id) else {", "guard true else {",
     "destroyLeavesForeignSandboxesUntouched"),
    ("create-journal", "Sources/IsoHost/Lifecycle/AppleLifecycle.swift",
     "    try Journal.complete(instance)\n  }\n\n  func provisionSandbox(",
     "  }\n\n  func provisionSandbox(",
     "createStopStartAndDestroyAgainstTheFakeRuntime"),
    ("config-writer-lock", "Sources/IsoHost/State/ConfigStore.swift",
     "let lock = try FileLock.sibling(of: path)\n    defer { lock.release() }\n", "",
     "concurrentProxyEditsAreAllRetained"),
    ("remote-command-escaping", "Sources/IsoCore/RemoteCommand.swift",
     "if character == \"'\" { escaped += \"'\\\\''\" } else { escaped.append(character) }",
     "escaped.append(character)",
     "remoteCommandEscapesArgumentsOnce"),
    ("env-forward-redaction", "Sources/IsoHost/Guest/GuestSession.swift",
     "\"\\(debugQuoted($0)): \\\"<redacted>\\\"\"", "\"\\($0)=\\(values[$0]!.expose())\"",
     "remoteCommandEscapesArgumentsOnce"),
    ("workspace-excludes", "Sources/IsoHost/Workspace/Workspace.swift",
     "let defaultExcludes = [\"node_modules/\", ", "let defaultExcludes = [",
     "tarPipeCopiesTheProjectAndSkipsExcludes"),
    ("ssh-config-user-alias", "Sources/IsoHost/Guest/SSHConfig.swift",
     "try SSHConfigBlocks.checkAliasAvailable(existing, host: host)", "",
     "sshConfigBlocksLeaveOtherNamespacesAlone"),
    ("mount-workspace-collision", "Sources/IsoHost/Workspace/Workspace.swift",
     "if let collision, mounts.contains(where: { $0.guestPath == guestWorkspace }) {",
     "if let collision, mounts.isEmpty {",
     "mountSetsRejectWorkspaceCollisionsAndDuplicates"),
    ("forward-port-probe", "Sources/IsoHost/Guest/PortForwards.swift",
     "if let failure = probe(forward.host) {", "if let failure = Optional<Int32>.none {",
     "forwardStateRoundTripsAndBusyPortsAreRefused"),
    ("github-token-stdin", "Sources/IsoHost/Credentials/GitHubAPI.swift",
     "if token != nil { arguments += [\"-H\", \"@-\"] }",
     "if let token { arguments += [\"-H\", \"Authorization: token \\(token.expose())\"] }",
     "tokensReachCurlOnStdinOnly"),
    ("update-checksum", "Sources/IsoHost/Update/Update.swift",
     "guard actual == expected else {", "guard actual == expected || true else {",
     "verifySHA256AcceptsTheRightDigestOnly"),
    ("update-complete-companions", "Sources/IsoHost/Update/Update.swift",
     'guard isRegularArtifact(extractDirectory + "/" + egressName) else {',
     "guard true else {",
     "missingCompanionsPreserveTheInstall"),
    ("update-regular-artifacts", "Sources/IsoHost/Update/Update.swift",
     "return lstat(path, &status) == 0 && (status.st_mode & S_IFMT) == S_IFREG",
     "return stat(path, &status) == 0 && (status.st_mode & S_IFMT) == S_IFREG",
     "nonRegularReleaseMembersPreserveTheInstall"),
    ("update-host-preflight", "Sources/IsoHost/Update/Update.swift",
     "guard SelfReplace.isRegularArtifact(extracted) else {",
     "guard pathExists(extracted) else {",
     "nonRegularReleaseMembersPreserveTheInstall"),
    ("update-attestation-repo", "Sources/IsoHost/Update/UpdateRelease.swift",
     "var arguments = [\"attestation\", \"verify\", tarball, \"--repo\", UpdateChannel.repository]",
     "var arguments = [\"attestation\", \"verify\", tarball]",
     "attestationArgumentsPinTheRepository"),
    ("update-attestation-signer", "Sources/IsoHost/Update/UpdateRelease.swift",
     "\"--cert-identity\", UpdateChannel.signerIdentity(tag: tag), \"--source-ref\",\n      \"refs/tags/\\(tag)\", \"--deny-self-hosted-runners\",",
     "",
     "attestationArgumentsPinTheRepository"),
    ("update-signature", "Sources/IsoHost/Update/Update.swift",
     "do { try SSHSignature.verify(armored: armored, message: bytes, trusted: signers) } catch {",
     "do { _ = armored } catch {",
     "unsignedOrForeignSignedSumsAreRefusedBeforeUse"),
    ("update-anti-rollback", "Sources/IsoHost/Update/Update.swift",
     "if target < current && !options.allowDowngrade {", "if false {",
     "olderReleasesNeedAllowDowngrade"),
    ("update-revoked-digest", "Sources/IsoHost/Update/Update.swift",
     "guard !revoked.contains(expected) else {", "guard true else {",
     "revokedArchivesAreRefused"),
    ("sshsig-trusted-key", "Sources/IsoHost/Update/ReleaseSignature.swift",
     "guard trusted.contains(key) else", "guard trusted.contains(key) || true else",
     "sshSignatureVerifiesOnlyTheSignedBytesFromATrustedKey"),
    ("sshsig-namespace", "Sources/IsoHost/Update/ReleaseSignature.swift",
     "guard signedNamespace == Array(namespace.utf8) else {",
     "guard signedNamespace == Array(namespace.utf8) || true else {",
     "sshSignatureVerifiesOnlyTheSignedBytesFromATrustedKey"),
    ("proxy-fail-closed", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     "    } catch {\n      stop(instance, provider: provider)\n      throw error\n    }\n    diagnostics.log(",
     "    } catch {\n    }\n    diagnostics.log(",
     "proxyStartFailsClosed"),
    ("keychain-no-fallback", "Sources/IsoHost/Credentials/SecretStore.swift",
     "    guard isAvailable else {\n      throw HostError(\n        \"macOS Keychain is unavailable",
     "    guard isAvailable || true else {\n      throw HostError(\n        \"macOS Keychain is unavailable",
     "missingKeychainFailsWithoutFallback"),
    ("mcp-definition-stdin", "Sources/IsoHost/Guest/BootstrapClaude.swift",
     "            \" \\\"$(cat)\\\"\"),\n          stdin: Array(resolved.json.compact.utf8))",
     "            \" \").arg(resolved.json.compact),\n          stdin: [])",
     "firstBootBootstrapConfiguresBothAgents"),
    ("transport-environment", "Sources/IsoHost/Guest/SSH.swift",
     "    self.environment = Self.transportEnvironment(environment)",
     "    self.environment = environment",
     "guestTransportCarriesOnlyForwardedVariables"),
    ("pid-file-identity", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     "      if let command = Self.commandLine(pid), expect.matches(command) {",
     "      if true {",
     "aReusedPIDIsNotSignalled"),
    ("proxy-port-free", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     "    let deadline = ContinuousClock.now + .seconds(2)\n    while Self.accepts(port: port) {",
     "    let deadline = ContinuousClock.now + .seconds(2)\n    while false {",
     "occupiedProxyPortsAreRefusedAndForeignListenersRejected"),
    ("proxy-listener-identity", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     "    guard listeners == [pid] else {", "    guard listeners == [pid] || true else {",
     "occupiedProxyPortsAreRefusedAndForeignListenersRejected"),
    ("feature-layer-digest", "Sources/IsoHost/Devcontainer/DevcontainerOCI.swift",
     "    guard sha256Hex(bytes) == expected.hash.rawValue else {",
     "    guard sha256Hex(bytes) == expected.hash.rawValue || true else {",
     "resolverFetchesOCIFeaturesWithBaselineArgv"),
    ("feature-read-nofollow", "Sources/IsoHost/Devcontainer/DevcontainerOCI.swift",
     "    let fd = open(path, O_RDONLY | O_NOFOLLOW | O_NONBLOCK | O_CLOEXEC)",
     "    let fd = open(path, O_RDONLY | O_NONBLOCK | O_CLOEXEC)",
     "featureFilesAreReadOnlyAsBoundedRegularFiles"),
    ("stage-symlink-containment", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "guard let target, Self.staysInside(link: path, target: target) else {",
     "guard let target else {",
     "escapingSymlinksMakeTheStageInapplicable"),
    ("proxy-required-codex-auth", "Sources/IsoHost/Guest/BootstrapCodex.swift",
     "    proxyActive || proxyMode == .required || egress == .none || auth == .chatgpt",
     "    proxyActive || egress == .none || auth == .chatgpt",
     "codexAuthJSONIsStagedOnlyForDirectAPIKeyMode"),
    ("egress-none-withholds", "Sources/IsoHost/Guest/Bootstrap.swift",
     "      guard proxied || required || noEgress else { continue }",
     "      guard proxied || required else { continue }",
     "egressNoneNeverForwardsARawProviderKey"),
    ("proxy-required-withholds", "Sources/IsoHost/Guest/Bootstrap.swift",
     "guard proxied || required || noEgress else { continue }",
     "guard proxied || noEgress else { continue }",
     "requiredModeWithholdsEveryProviderVariableAndRefusesDeclarations"),
    ("proxy-off-ignores-upstreams", "Sources/IsoHost/Guest/ProxyUpstreams.swift",
     "    guard config.mode != .off else { return nil }\n", "",
     "offModeIgnoresConfiguredUpstreams"),
    ("proxy-required-start", "Sources/IsoHost/Guest/Bootstrap.swift",
     "    guard !configured else { return }\n", "    guard configured else { return }\n",
     "requiredModeFailsStartWithoutAnyProviderProxy"),
    ("vault-refused-for-guest-values", "Sources/IsoHost/Credentials/CredentialResolver.swift",
     "    if raw.hasPrefix(\"vault:\") {\n      throw HostError(", "    if false {\n      throw HostError(",
     "vaultIsRefusedForValuesPlacedInTheGuest"),
    ("proxy-state-reference", "Sources/IsoHost/Credentials/ProxyState.swift",
     'guard let reference = CredentialReference(credential) else {',
     'guard let reference = CredentialReference(credential) ?? CredentialReference("cmd:fault") else {',
     "proxyOverridesResolveAndRejectLiteralCredentials"),
    ("guest-env-version", "Sources/IsoHost/Guest/GuestEnvState.swift",
     '      members["version"] == .number(.integer(2))',
     '      true || members["version"] == .number(.integer(2))',
     "guestEnvStateRequiresCurrentVersionAndTypedEntries"),
    ("credential-separation", "Sources/IsoHost/Guest/GuestEnvState.swift",
     "        credentials.contains(name)\n", "        false\n",
     "aStoredSecretIsEitherAProxyCredentialOrGuestVisible"),
    ("preset-provider-only", "Sources/IsoConfiguration/IsoConfig.swift",
     "    case .providerOnly: .required\n", "    case .providerOnly: .auto\n",
     "securityPresetsSupplyDefaultsThatExplicitFieldsOverride"),
    ("audit-records-boot", "Sources/IsoHost/Guest/Bootstrap.swift",
     "    recordBoot(instance)\n", "",
     "requiredModeFailsStartWithoutAnyProviderProxy"),
    ("session-expiry-gate", "Sources/IsoHost/Runtime/IsolationGate.swift",
     "      if deadline <= Date() {",
     "      if deadline < Date.distantPast {",
     "anExpiredSessionIsNotHandedOut"),
    ("session-deadline-unreadable", "Sources/IsoHost/Runtime/IsolationGate.swift",
     "if let recorded = inspection.record.expiresAt {",
     "if let recorded = inspection.record.expiresAt, inspection.record.sessionDeadline != nil {",
     "anUnreadableSessionDeadlineIsNotTreatedAsNoLimit"),
    ("session-ttl-on-restart", "Sources/IsoHost/Lifecycle/AppleLifecycle.swift",
     "        runtime, expected(sidecar, runtime), until: deadline, sessionTTL: config.limits.sessionTTL)",
     "        runtime, expected(sidecar, runtime), until: deadline)",
     "sessionTTLPassesAnExpiryToEveryBoot"),
    ("egress-record-mode", "Sources/IsoHost/Runtime/IsolationGate.swift",
     "guard hostOnly == expected.egress.requiresHostOnlyNetwork else {", "guard hostOnly || !hostOnly else {",
     "egressIsCheckedOnTheRecordBeforeBoot"),
    ("egress-interface-label", "Sources/IsoHost/Runtime/IsolationGate.swift",
     "let prefix = egress.requiresHostOnlyNetwork ? \"vmnet-host:10.231.\" : \"vmnet-shared:10.231.\"",
     "let prefix = \"vmnet-\"",
     "egressNoneRequiresAHostOnlySandbox"),
    ("provider-secret-skips-guest", "Sources/IsoHost/Guest/Bootstrap.swift",
     "          if routed.contains(name) { continue }\n", "",
     "providerSecretsNeverReachTheGuestAndSelectTheProxy"),
    ("provider-secret-off-unavailable", "Sources/IsoHost/Guest/ProxyUpstreams.swift",
     "      guard config.mode != .off else { throw unavailable(routed) }\n", "",
     "providerSecretsNeverReachTheGuestAndSelectTheProxy"),
    ("secrets-device-key-digest", "Sources/IsoSecrets/DeviceFactor.swift",
     "(1...4096).contains(data.count), Self.digest(Array(data)) == sha256",
     "(1...4096).contains(data.count)",
     "missingOrCorruptDeviceKeyIsPermanentAndMintsNothing"),
    ("secrets-kdf-bounds", "Sources/IsoSecrets/KDF.swift",
     "guard r == 8, p == 1 else {", "guard r > 0, p > 0 else {",
     "scryptParametersAreBoundedBeforeUse"),
    ("secrets-envelope-aad", "Sources/IsoSecrets/StoreFormat.swift",
     "plaintext, using: key, nonce: nonce, authenticating: additionalData(parameters))",
     "plaintext, using: key, nonce: nonce)",
     "envelopeBindsTheKDFParameters"),
    ("stage-symlink-chains", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "    try checkLinkChains()\n", "",
     "symlinkChainsCannotEscape"),
    ("stage-chain-fold", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "let staged = Set(links.map { Self.folded($0.path) })",
     "let staged = Set(links.map(\\.path))",
     "symlinkChainsAreDetectedCaseInsensitively"),
    ("stage-conspicuous-git", "Sources/IsoHost/Workspace/WorkspaceStageReview.swift",
     "if let git = components.firstIndex(of: \".git\") {",
     "if let git = components.firstIndex(of: \".git-none\") {",
     "conspicuousPathsIgnoreCase"),
    ("stage-growth-bytes", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "if bytes > limits.maxBytes.bytes + entries * Self.blockSlack {", "if bytes < 0 {",
     "growthGuardStopsATransferThatOutgrowsTheBudget"),
    ("stage-depth", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "guard depth < Self.maxDepth else {", "guard depth >= 0 else {",
     "deeplyNestedDirectoriesAreRefusedNotWalked"),
    ("stage-growth-files", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "if entries > limits.maxFiles {", "if entries < 0 {",
     "growthGuardStopsATransferThatOutgrowsTheBudget"),
    ("stage-conspicuous-husky", "Sources/IsoHost/Workspace/WorkspaceStageReview.swift",
     "if components.contains(\".husky\")", "if components.contains(\".husky-none\")",
     "conspicuousPathsIgnoreCase"),
    ("stage-conspicuous-envrc", "Sources/IsoHost/Workspace/WorkspaceStageReview.swift",
     "if components.last == \".envrc\"", "if components.last == \".envrc-none\"",
     "conspicuousPathsIgnoreCase"),
    ("stage-conspicuous-vscode", "Sources/IsoHost/Workspace/WorkspaceStageReview.swift",
     "if components.suffix(2) == [\".vscode\", \"tasks.json\"]",
     "if components.suffix(2) == [\".vscode\", \"tasks-none.json\"]",
     "conspicuousPathsIgnoreCase"),
    ("stage-conspicuous-hooks", "Sources/IsoHost/Workspace/WorkspaceStageReview.swift",
     "if rest.contains(\"hooks\")", "if rest.contains(\"hooks-none\")",
     "reviewShowsChangesDiffsAndConspicuousPaths"),
    ("audit-append", "Sources/IsoHost/State/BoundaryAudit.swift",
     "O_WRONLY | O_CREAT | O_APPEND | O_NOFOLLOW", "O_WRONLY | O_CREAT | O_NOFOLLOW",
     "concurrentRecordersLoseNoEvents"),
    ("destroy-stage-first", "Sources/IsoHost/Lifecycle/AppleLifecycle.swift",
     "    try stage.remove()\n", "",
     "destroyRemovesStagesWithGuestChosenModes"),
    ("stage-lock-stage", "Sources/IsoHost/Workspace/Workspace.swift",
     "    let lock = try location.lock()\n    defer { lock.release() }\n    try location.prepare()\n",
     "    try location.prepare()\n",
     "stagedTransferWaitsForTheLockAndStopsWhenItOutgrowsTheBudget"),
    ("stage-lock-apply", "Sources/IsoHost/Workspace/Workspace.swift",
     "    let lock = try location.lock()\n    defer { lock.release() }\n    let manifest = try location.loadManifest()\n",
     "    let manifest = try location.loadManifest()\n",
     "applyAndDiscardWaitForTheStageLock"),
    ("stage-lock-discard", "Sources/IsoHost/Workspace/Workspace.swift",
     "    let lock = try location.lock()\n    defer { lock.release() }\n    guard location.exists else { return false }\n",
     "    guard location.exists else { return false }\n",
     "applyAndDiscardWaitForTheStageLock"),
    ("stage-growth-wiring", "Sources/IsoHost/Workspace/Workspace.swift",
     "sparse: true, cancel: growth.shouldCancel)", "sparse: true, cancel: nil)",
     "stagedTransferWaitsForTheLockAndStopsWhenItOutgrowsTheBudget"),
    ("stage-rsync-wiring", "Sources/IsoHost/Workspace/Workspace.swift",
     "preserveLinks: true, cancel: growth.shouldCancel)", "preserveLinks: true, cancel: nil)",
     "stagedTransferWaitsForTheLockAndStopsWhenItOutgrowsTheBudget"),
    ("stage-rsync-cancel", "Sources/IsoHost/Workspace/Workspace.swift",
     "    rsync.isCancelled = cancel\n", "",
     "stagedTransferWaitsForTheLockAndStopsWhenItOutgrowsTheBudget"),
    ("stage-tar-cancel", "Sources/IsoHost/Workspace/Workspace.swift",
     "    producer.isCancelled = cancel\n", "",
     "stagedTransferWaitsForTheLockAndStopsWhenItOutgrowsTheBudget"),
    ("runner-kills-descendants", "Sources/IsoHost/Processes/ProcessRunner.swift",
     "        for pid in Self.descendants(of: child.pid).reversed() { kill(pid, SIGKILL) }\n", "",
     "cancellingAnAttachedRequestKillsItsDescendants"),
    ("stage-hard-links", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "guard info.st_nlink == 1 else {", "guard info.st_nlink >= 1 else {",
     "specialFilesHardLinksAndBadNamesAreIssues"),
    ("stage-byte-budget", "Sources/IsoHost/Workspace/WorkspaceStage.swift",
     "guard bytes <= limits.maxBytes.bytes else {", "guard bytes >= 0 else {",
     "budgetsAbortStaging"),
    ("stage-destination-drift", "Sources/IsoHost/Workspace/WorkspaceStageApply.swift",
     "if now != change.old { drifted.append(change.path) }", "_ = now",
     "destinationDriftSinceReviewIsRefusedBeforeWriting"),
    ("stage-content-digest", "Sources/IsoHost/Workspace/WorkspaceStageApply.swift",
     "guard copied == digest else {", "guard copied == digest || true else {",
     "stageTamperingAfterReviewIsRefused"),
    ("agent-unknown-field", "Sources/IsoConfiguration/AgentDefinition.swift",
     """    try reader.rejectUnknown(allowing: [
      "schema_version", "id", "display_name", "environment", "launch", "auth_adapter",
      "network_hints",
    ])""",
     "",
     "definitionRejectsUnknownFieldsAndBudgets"),
    ("agent-env-allowlist", "Sources/IsoConfiguration/AgentDefinition.swift",
     "guard AgentEnvironmentAllowlist.names.contains(key) else {",
     "guard true || AgentEnvironmentAllowlist.names.contains(key) else {",
     "definitionRejectsUnknownFieldsAndBudgets"),
    ("agent-catalog-nofollow", "Sources/IsoHost/Guest/AgentCatalog.swift",
     "let fd = open(path, O_RDONLY | O_CLOEXEC | O_NOFOLLOW)",
     "let fd = open(path, O_RDONLY | O_CLOEXEC)",
     "catalogInstallUsesTheReviewedValueAndRejectsSymlinks"),
    ("create-provider-preflight", "Sources/IsoHost/Lifecycle/ProjectLifecycle.swift",
     "instance, noAgents: options.boot.noAgents,", "instance, noAgents: true,",
     "providerProxyRequirementFailsStartAndRestartBeforeAnyVmWork"),
    ("restart-provider-preflight", "Sources/IsoHost/Lifecycle/ProjectLifecycle.swift",
     "instance, noAgents: options.noAgents, guestEnvironment: guestEnvironment)",
     "instance, noAgents: true, guestEnvironment: guestEnvironment)",
     "providerProxyRequirementFailsStartAndRestartBeforeAnyVmWork"),
    ("sidecar-lifecycle", "Sources/IsoHost/State/StateStore.swift",
     "copy.lifecycle = .disposable", "copy.lifecycle = .reusable",
     "sidecarLifecycleIsRequiredAndClosed"),
    ("current-runtime-protocol", "Sources/IsoHost/Runtime/SandboxRuntime.swift",
     "version.protocol == RuntimeProtocol.version", "version.protocol <= RuntimeProtocol.version",
     "qualificationAcceptsOnlyTheValidatedRuntime"),
    ("disposable-affinity", "Sources/IsoHost/Lifecycle/RunSession.swift",
     "marker.lifecycle == .disposable",
     "marker.lifecycle == .reusable",
     "disposableMarkerIsNotAnAffinityCandidateAndCleanupRequiresProof"),
    ("filtered-github-replacement", "Sources/IsoConfiguration/GitHubConfigEdits.swift",
     "egressFilter: egressFilter, limits: limits,\n      securityPreset: securityPreset)\n  }\n\n  /// `up`",
     "egressFilter: .empty, limits: limits,\n      securityPreset: securityPreset)\n  }\n\n  /// `up`",
     "configurationOverlaysPreserveFilteredDestinations"),
    ("filtered-github-disabled", "Sources/IsoConfiguration/GitHubConfigEdits.swift",
     "egressFilter: egressFilter, limits: limits,\n      securityPreset: securityPreset)\n  }\n}\n\n/// A verified",
     "egressFilter: .empty, limits: limits,\n      securityPreset: securityPreset)\n  }\n}\n\n/// A verified",
     "configurationOverlaysPreserveFilteredDestinations"),
    ("filtered-devcontainer-overlay", "Sources/IsoConfiguration/IsoConfigDevcontainer.swift",
     "egress: egress, egressFilter: egressFilter, limits: limits",
     "egress: egress, egressFilter: .empty, limits: limits",
     "configurationOverlaysPreserveFilteredDestinations"),
    ("filtered-boot-protocol", "Sources/IsoHost/Runtime/RuntimeProtocol.swift",
     "advertised == bootIdentity && !(bootID?.isEmpty ?? true)",
     "advertised == bootIdentity || advertised == 4",
     "filteredBootRequiresProtocolFiveAndALiveBootID"),
    ("filtered-lease-deadline", "Sources/IsoHost/Runtime/EgressLease.swift",
     "&& livePID == expectedPID && sessionOpen && ownerAlive",
     "&& livePID == expectedPID && ownerAlive",
     "egressLeaseStopsWhenTheRecordedOwnerChanges"),
    ("filtered-lease-owner", "Sources/IsoHost/Runtime/EgressLease.swift",
     "&& sessionOpen && ownerAlive",
     "&& sessionOpen",
     "egressLeaseStopsWhenTheRecordedOwnerChanges"),
    ("image-apt-download-bounds", "Sources/IsoHost/Guest/ImageBuild.swift",
     '"-o Acquire::Retries=2 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30"',
     '"-o Acquire::Retries=0"',
     "imageAPTCommandsExposeProgressAndBoundRepositoryReads"),
    ("filtered-lease-live-decoder", "Sources/IsoHost/Runtime/EgressLease.swift",
     'let live = try? JSONDecoder().decode(LiveIdentity.self, from: Data(bytes)),',
     'let live = Optional(LiveIdentity(bootId: "boot", pid: 7)),',
     "egressLeaseRejectsInvalidOwnerPIDs"),
    ("filtered-lease-positive-pid", "Sources/IsoHost/Runtime/EgressLease.swift",
     'live.pid > 0, !live.bootId.isEmpty', 'true, !live.bootId.isEmpty',
     "egressLeaseRejectsInvalidOwnerPIDs"),
    ("filtered-lease-session-decoder", "Sources/IsoHost/Runtime/EgressLease.swift",
     'let record = try? decoder.decode(SessionRecord.self, from: Data(bytes))',
     'let record = Optional(SessionRecord(expiresAt: nil))',
     "egressLeaseRejectsMalformedSessionDeadlines"),
    ("filtered-lease-lock-error", "Sources/IsoHost/Runtime/EgressLease.swift",
     'return errno == EWOULDBLOCK || errno == EAGAIN', 'return true',
     "egressLeaseDoesNotMistakeLockProbeErrorsForContention"),
    ("filtered-lease-live-file", "Sources/IsoHost/Runtime/EgressLease.swift",
     'StateStore.readControlFile(path)', 'Array(Data(contentsOf: URL(fileURLWithPath: path)))',
     "egressLeaseControlFilesAreBoundedRegularFilesWithoutSymlinks"),
    ("filtered-lease-record-file", "Sources/IsoHost/Runtime/EgressLease.swift",
     'StateStore.readControlFile(recordPath)', 'Array(Data(contentsOf: URL(fileURLWithPath: recordPath)))',
     "egressLeaseControlFilesAreBoundedRegularFilesWithoutSymlinks"),
    ("runtime-owner-demand", "iso-sandbox/Sources/IsoSandboxCore/Launchd.swift",
     'request([launchctl, "kickstart", target])', '(status: Int32(0), output: "")',
     "launchdDemandsAnOwnerWithoutKillingAnExistingOne"),
    ("runtime-owner-background-domain", "iso-sandbox/Sources/IsoSandboxCore/Launchd.swift",
     '"user/\\(getuid())"', '"gui/\\(getuid())"',
     "launchdJobRestartsOnlyAbnormalExitsWithAFixedEnvironment"),
    ("runtime-owner-background-session", "iso-sandbox/Sources/IsoSandboxCore/Launchd.swift",
     '"LimitLoadToSessionType": "Background",', '"LimitLoadToSessionType": "Aqua",',
     "launchdJobRestartsOnlyAbnormalExitsWithAFixedEnvironment"),
    ("runtime-owner-no-kill", "iso-sandbox/Sources/IsoSandboxCore/Launchd.swift",
     'request([launchctl, "kickstart", target])', 'request([launchctl, "kickstart", "-k", target])',
     "launchdDemandsAnOwnerWithoutKillingAnExistingOne"),
    ("runtime-owner-rollback", "iso-sandbox/Sources/IsoSandboxCore/Launchd.swift",
     'request([launchctl, "bootout", target])', '(status: Int32(0), output: "")',
     "launchdStartupFailurePreservesItsCauseAndCleansOnlyItsJob"),
    ("runtime-owner-demand-error", "iso-sandbox/Sources/IsoSandboxCore/Launchd.swift",
     "guard started.status == 0 else {", "guard true else {",
     "launchdStartupFailurePreservesItsCauseAndCleansOnlyItsJob"),
    ("admin-completion-owner", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'current.ready == expected.ready', 'true', "bootstrapCompletionRetainsOriginalTransportIdentity"),
    ("admin-completion-target", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'current.target == expected.target', 'true', "bootstrapCompletionRetainsOriginalTransportIdentity"),
    ("admin-completion-wire", "Sources/IsoHost/Runtime/AppleBackend.swift",
     'try WorkloadHandoff.requireTransport(preparation, running)', '// fault: adopt replacement transport',
     "bootstrapCompletionDoesNotAdoptAReplacementProof"),
    ("admin-completion-policy", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'current.handoffIdentity?.policy == identity.policy', 'true',
     "bootstrapCompletionRetainsOriginalTransportIdentity"),
    ("admin-completion-egress", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'current.handoffIdentity?.egressKey == identity.egressKey', 'true',
     "bootstrapCompletionRetainsOriginalTransportIdentity"),
    ("admin-version-refusal", "Sources/IsoHost/Guest/AgentUpdate.swift",
     '} catch let failure as GuestHandoffFailure {\n      throw failure\n    } catch { return nil }',
     '} catch { return nil }', "agentUpdatePreservesReadinessFailuresInsteadOfReportingUnknownOrContinuing"),
    ("admin-update-refusal", "Sources/IsoHost/Guest/AgentUpdate.swift",
     '} catch let failure as GuestHandoffFailure {\n        throw failure\n      } catch {\n        failed = true',
     '} catch {\n        failed = true', "agentUpdatePreservesReadinessFailuresInsteadOfReportingUnknownOrContinuing"),
    ("admin-codex-refusal", "Sources/IsoHost/Guest/AgentUpdate.swift",
     'stdin: Array(EmbeddedResources.guestScript("codex.sh").utf8))\n      } catch let failure as GuestHandoffFailure {\n        throw failure\n      } catch {',
     'stdin: Array(EmbeddedResources.guestScript("codex.sh").utf8))\n      } catch {',
     "agentUpdatePreservesReadinessFailuresInsteadOfReportingUnknownOrContinuing"),
    ("admin-claude-refusal", "Sources/IsoHost/Guest/AgentUpdate.swift",
     'RemoteCommand().arg(binary(agent, user: session.target.user).rawValue).literal(" update"))\n      } catch let failure as GuestHandoffFailure {\n        throw failure\n      } catch {',
     'RemoteCommand().arg(binary(agent, user: session.target.user).rawValue).literal(" update"))\n      } catch {',
     "agentUpdatePreservesReadinessFailuresInsteadOfReportingUnknownOrContinuing"),
    ("admin-forward", "Sources/IsoHost/Guest/PortForwards.swift",
     'try target.requireHandoff()\n      output = try client.runner.capture', 'output = try client.runner.capture',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-reverse-cleanup", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     '} catch {\n      master.kill()\n      throw ContextError(', '} catch {\n      throw ContextError(',
     "reverseForwardRechecksBeforeMasterAndRequestAndCleansOnRefusal"),
    ("admin-reverse-master", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     'try target.requireHandoff()\n      master = try DetachedChild.spawn', 'master = try DetachedChild.spawn',
     "reverseForwardRechecksBeforeMasterAndRequestAndCleansOnRefusal"),
    ("admin-reverse-request", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     'try target.requireHandoff()\n        request = try DetachedChild.spawn', 'request = try DetachedChild.spawn',
     "reverseForwardRechecksBeforeMasterAndRequestAndCleansOnRefusal"),
    ("admin-rsync-probe", "Sources/IsoHost/Workspace/Workspace.swift",
     'try client.succeedsChecked(target, RemoteCommand().literal("which rsync"))',
     'client.succeeds(target, RemoteCommand().literal("which rsync"))',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-target-bind", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'return expected.target.validating { try require(expected, inspect: inspect) }', 'return expected.target',
     "administrativeTargetsRetainOriginalIdentityAndNonfilteredCompatibility"),
    ("admin-target-check", "Sources/IsoHost/Guest/SSH.swift",
     'do { try handoffCheck?() } catch { throw GuestHandoffFailure(cause: error) }', 'return',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-exec-target", "Sources/IsoHost/Guest/GuestSession.swift",
     'package func exec(_ target: SSHTarget, _ command: RemoteCommand) throws {\n    try target.requireHandoff()',
     'package func exec(_ target: SSHTarget, _ command: RemoteCommand) throws {',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-exec-session", "Sources/IsoHost/Guest/GuestSession.swift",
     'package func exec(_ session: SSHSession, _ command: RemoteCommand) throws {\n    try session.target.requireHandoff()',
     'package func exec(_ session: SSHSession, _ command: RemoteCommand) throws {',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-input-session", "Sources/IsoHost/Guest/GuestSession.swift",
     'package func exec(_ session: SSHSession, _ command: RemoteCommand, stdin: [UInt8]) throws {\n    try session.target.requireHandoff()',
     'package func exec(_ session: SSHSession, _ command: RemoteCommand, stdin: [UInt8]) throws {',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-input-target", "Sources/IsoHost/Guest/GuestSession.swift",
     'let arguments = target.sshOptions + [target.address, command.rendered]\n    try target.requireHandoff()',
     'let arguments = target.sshOptions + [target.address, command.rendered]',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-succeeds", "Sources/IsoHost/Guest/GuestSession.swift",
     'guard let ssh = sshExecutable() else { return false }\n    try target.requireHandoff()', 'guard let ssh = sshExecutable() else { return false }',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-capture", "Sources/IsoHost/Guest/SSH.swift",
     'guard let ssh = sshExecutable(), (try? target.requireHandoff()) != nil else { return nil }',
     'guard let ssh = sshExecutable() else { return nil }', "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-checked-capture", "Sources/IsoHost/Guest/GuestSession.swift",
     'package func captureChecked(_ target: SSHTarget, _ command: RemoteCommand) throws -> String {\n    try target.requireHandoff()',
     'package func captureChecked(_ target: SSHTarget, _ command: RemoteCommand) throws -> String {',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-copy", "Sources/IsoHost/Guest/GuestSession.swift",
     'guard let scp = executable(named: "scp") else { throw HostError("Failed to run scp") }\n    try target.requireHandoff()',
     'guard let scp = executable(named: "scp") else { throw HostError("Failed to run scp") }',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-wait", "Sources/IsoHost/Guest/SSH.swift",
     '      try target.requireHandoff()\n      let probe =', '      let probe =',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-tar-push", "Sources/IsoHost/Workspace/Workspace.swift",
     'let extract = RemoteCommand().literal("tar xf - -C ").arg(guest.rawValue)\n    try target.requireHandoff()',
     'let extract = RemoteCommand().literal("tar xf - -C ").arg(guest.rawValue)',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-tar-pull", "Sources/IsoHost/Workspace/Workspace.swift",
     'producer.isCancelled = cancel\n    try target.requireHandoff()', 'producer.isCancelled = cancel',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-rsync-push", "Sources/IsoHost/Workspace/Workspace.swift",
     'try target.requireHandoff()\n    guard\n      try runner.attached(request(try tool("rsync"), arguments)',
     'guard\n      try runner.attached(request(try tool("rsync"), arguments)', "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-rsync-pull", "Sources/IsoHost/Workspace/Workspace.swift",
     'rsync.isCancelled = cancel\n    try target.requireHandoff()', 'rsync.isCancelled = cancel',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-dirty-check", "Sources/IsoHost/Workspace/Workspace.swift",
     '// non-empty, so it reports the changes rather than an I/O error.\n      try target.requireHandoff()',
     '// non-empty, so it reports the changes rather than an I/O error.', "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-hook-refusal", "Sources/IsoHost/Guest/Bootstrap.swift",
     '} catch let failure as GuestHandoffFailure {\n      throw failure\n    } catch {', '} catch {',
     "postStartStillWarnsOnGuestFailureButPropagatesReadinessFailure"),
    ("admin-alias", "Sources/IsoHost/Guest/SSHConfig.swift",
     'try target.requireHandoff()\n    try write(cleaned.isEmpty', 'try write(cleaned.isEmpty',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("admin-editor", "Sources/IsoHost/Editor/EditorLauncher.swift",
     '        try running.target.requireHandoff()', '        // fault: unchecked editor handoff',
     "administrativeHandoffsRefuseLateInvalidation"),
    ("editor-declined-fallback", "Sources/IsoHost/Editor/EditorLauncher.swift",
     'for provider in providers where declined == nil {', 'for provider in providers {',
     "legacyAutoDetectionTriesVSCodeThenZed"),
    ("editor-spawn-failure-fallback", "Sources/IsoHost/Editor/EditorLauncher.swift",
     'choice.isExplicit || timedOut {', 'timedOut {',
     "anEditorThatCannotBeSpawnedIsALaunchFailureNotAMissingEditor"),
    ("editor-auto-timeout-fallback", "Sources/IsoHost/Editor/EditorLauncher.swift",
     'choice.isExplicit || timedOut {', 'choice.isExplicit {',
     "aHangingEditorIsKilledAtTheDeadline"),
    ("editor-deadline", "Sources/IsoHost/Editor/EditorLauncher.swift",
     'inheritStdin: true, deadline: deadline)', 'inheritStdin: true, deadline: nil)',
     "aHangingEditorIsKilledAtTheDeadline"),
    ("attached-deadline", "Sources/IsoHost/Processes/ProcessRunner.swift",
     'let expired = deadline.map { ContinuousClock.now - start >= $0 } ?? false',
     'let expired = false', "attachedModeKillsAChildAtItsDeadline"),
    ("editor-failure-lifecycle", "Sources/IsoCLI/Support/MachineErrors.swift",
     'details: .after(after.lifecycle, cause.details))', 'details: cause.details)',
     "editorResultsCarryTheAliasAndLaunchTargetNeverKeyMaterial"),
    ("editor-command-single-provider", "Sources/IsoHost/Editor/ProjectEditorWorkflow.swift",
     'choice: .only(provider),', 'choice: .firstAvailable(EditorProviderID.allCases.map(\\.provider)),',
     "projectEditorCommandsLaunchOnlyTheirProviderAndReportTheLifecycleStep"),
    ("editor-unsafe-environment", "Sources/IsoHost/Editor/EditorLauncher.swift",
     'environment: spawnEnvironment,', 'environment: environment,',
     "unsafeLaunchersInheritNoCallerSecrets"),
    ("editor-sandboxed-handoff", "Sources/IsoHost/Editor/EditorLauncher.swift",
     '      try running.target.requireHandoff()\n      try SandboxedEditorSession(',
     '      try SandboxedEditorSession(',
     "aSandboxedLaunchRefusesALateHandoffFailureBeforeAnySetup"),
    ("editor-signature", "Sources/IsoHost/Editor/TrustedEditorApp.swift",
     '      try verifySignature(bundle, identity)', '      _ = identity',
     "editorAppsComeOnlyFromVerifiedBundles"),
    ("editor-bundle-ownership", "Sources/IsoHost/Editor/TrustedEditorApp.swift",
     'guard status.st_uid == 0 || status.st_uid == uid, status.st_mode & 0o022 == 0 else {',
     'guard status.st_uid == 0 || status.st_uid == uid else {',
     "editorAppsComeOnlyFromVerifiedBundles"),
    ("editor-profile-deny-default", "Sources/IsoHost/Editor/EditorSandboxProfile.swift",
     '    (deny default)', '    (allow default)',
     "theEditorProfileIsDenyByDefaultAndWidensOnlyOnRequest|seatbeltConfinesTheEditorToItsSessionAndTunnel"),
    ("editor-profile-capabilities", "Sources/IsoHost/Editor/EditorSandboxProfile.swift",
     'for capability in capabilities {', 'for capability in EditorHostCapability.allCases {',
     "theEditorProfileIsDenyByDefaultAndWidensOnlyOnRequest"),
    ("editor-session-environment", "Sources/IsoHost/Editor/SandboxedEditorSession.swift",
     'environment: enclave.environment(caller: callerEnvironment)',
     'environment: callerEnvironment',
     "aSandboxedSessionAuthorizesConfinesAndCleansUp"),
    ("editor-session-revoke", "Sources/IsoHost/Editor/SandboxedEditorSession.swift",
     'defer { revoke(enclave.keyComment) }', 'defer { _ = enclave.keyComment }',
     "aSandboxedSessionAuthorizesConfinesAndCleansUp"),
    ("editor-session-enclave-removal", "Sources/IsoHost/Editor/SandboxedEditorSession.swift",
     'defer { enclave.remove() }', 'defer { _ = enclave }',
     "aSandboxedSessionAuthorizesConfinesAndCleansUp"),
    ("editor-session-supervision", "Sources/IsoHost/Editor/SandboxedEditorSession.swift",
     'if supervisor.lost {', 'if false {',
     "aLostReadinessProofEndsTheEditorSession"),
    ("editor-session-tunnel", "Sources/IsoHost/Editor/SandboxedEditorSession.swift",
     'if tunnel.hasExited() {\n        reason = .tunnelClosed', 'if false {\n        reason = .tunnelClosed',
     "aFailedEditorOrClosedTunnelEndsTheSession"),
    ("editor-sessions-directory-mode", "Sources/IsoHost/Editor/EditorEnclave.swift",
     'status.st_mode & 0o077 == 0\n', 'true\n',
     "theSessionsDirectoryMustBePrivateToThisUser"),
    ("up-egress-restart-only", "Sources/IsoHost/Lifecycle/UpWorkflow.swift",
     'try NetworkPolicy.enforce(instance, config: lifecycle.config)',
     'try? NetworkPolicy.enforce(instance, config: lifecycle.config)',
     "aRunningInstanceRefusesADifferentRequestedEgressPolicy"),
    ("admin-preparation", "Sources/IsoHost/Guest/Bootstrap.swift",
     'try session.target.requireHandoff()\n    return session', 'return session',
     "administrativePreparationRejectsInvalidatedTarget"),
    ("admin-bootstrap-brokers", "Sources/IsoHost/Runtime/AppleBackend.swift",
     'case .transport: [:]', 'case .transport: try prove()',
     "bootstrapProofDoesNotDemandFutureBrokersButCompositeProofDoes"),
    ("admin-composite-brokers", "Sources/IsoHost/Runtime/AppleBackend.swift",
     'case .composite: try prove()', 'case .composite: [:]',
     "bootstrapProofDoesNotDemandFutureBrokersButCompositeProofDoes"),
    ("workload-preparation-check", "Sources/IsoHost/Guest/GuestSession.swift",
     '    try revalidate()\n    self.session = session', '    self.session = session',
     "workloadConstructionRefusesPreparationInvalidatedReadiness"),
    ("workload-launch-reporting", "Sources/IsoHost/Guest/GuestSession.swift",
     '    try workload.revalidate()\n    let termination: ProcessRunner.Termination\n    do {\n      termination = try workload.attached(\n        client, client.request(ssh, arguments, environment: environment), inheritStdin: true)',
     '    let termination: ProcessRunner.Termination\n    do {\n      termination = try workload.attached(\n        client, client.request(ssh, arguments, environment: environment), inheritStdin: true)',
     "workloadLaunchRechecksImmediatelyBeforeSpawning"),
    ("workload-launch-shell", "Sources/IsoHost/Guest/GuestSession.swift",
     '    try workload.revalidate()\n    let termination: ProcessRunner.Termination\n    do {\n      termination = try workload.attached(\n        client, client.request(ssh, arguments(session, remote: remote), environment: environment),',
     '    let termination: ProcessRunner.Termination\n    do {\n      termination = try workload.attached(\n        client, client.request(ssh, arguments(session, remote: remote), environment: environment),',
     "workloadLaunchRechecksImmediatelyBeforeSpawning"),
    ("workload-launch-command", "Sources/IsoHost/Guest/GuestSession.swift",
     '    try workload.revalidate()\n    let termination = try workload.attached(\n      client,\n      client.request(\n        ssh, session.sshOptions + [session.target.address, remote],\n        environment: session.env.overlay(client.environment)),\n      inheritStdin: true)',
     '    let termination = try workload.attached(\n      client,\n      client.request(\n        ssh, session.sshOptions + [session.target.address, remote],\n        environment: session.env.overlay(client.environment)),\n      inheritStdin: true)',
     "workloadLaunchRechecksImmediatelyBeforeSpawning"),
    ("workload-launch-exec", "Sources/IsoHost/Guest/GuestSession.swift",
     '    try workload.revalidate()\n    let termination = try workload.attached(\n      client,\n      client.request(\n        ssh, session.sshOptions + [session.target.address, remote],\n        environment: session.env.overlay(client.environment)),\n      inheritStdin: false)',
     '    let termination = try workload.attached(\n      client,\n      client.request(\n        ssh, session.sshOptions + [session.target.address, remote],\n        environment: session.env.overlay(client.environment)),\n      inheritStdin: false)',
     "workloadLaunchRechecksImmediatelyBeforeSpawning"),
    ("workload-fresh-proof", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'guard let current = try inspect() else {', 'guard let current = Optional(expected) else {',
     "workloadHandoffRequiresFreshUnchangedIdentity"),
    ("workload-owner", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'guard expected.ready == current.ready,', 'guard true,',
     "workloadHandoffRequiresFreshUnchangedIdentity"),
    ("workload-target", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'expected.target == current.target,', 'true,',
     "workloadHandoffRequiresFreshUnchangedIdentity"),
    ("workload-identity", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'expected.handoffIdentity == current.handoffIdentity', 'true',
     "workloadHandoffRequiresFreshUnchangedIdentity"),
    ("workload-nonfiltered", "Sources/IsoHost/Runtime/WorkloadHandoff.swift",
     'guard expected.handoffIdentity != nil else { return }', '// fault: lost compatibility bypass',
     "workloadHandoffPreservesNonfilteredCompatibility"),
    ("broker-readiness-signature", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'return key.value.isValidSignature(signature, for: Data(message.utf8))', 'return true',
     "brokerReadinessRejectsSignedWrongFieldsAndForgery"),
    ("broker-readiness-nonce", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'reply.nonce == nonce,', 'true,', "brokerReadinessRejectsSignedWrongFieldsAndForgery"),
    ("broker-readiness-provider", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'reply.provider == provider.rawValue,', 'true,', "brokerReadinessRejectsSignedWrongFieldsAndForgery"),
    ("broker-readiness-boot", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'reply.bootID == policy.bootID,', 'true,', "brokerReadinessRejectsSignedWrongFieldsAndForgery"),
    ("broker-readiness-policy", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'reply.policyHash == policy.policyHash,', 'true,', "brokerReadinessRejectsSignedWrongFieldsAndForgery"),
    ("broker-readiness-version", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'reply.version == 1,', 'true,', "brokerReadinessRejectsSignedWrongFieldsAndForgery"),
    ("broker-readiness-framing", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'headers[1].lowercased() == "content-length: \\(body.count)",', 'true,',
     "brokerReadinessRejectsSignedWrongFieldsAndForgery"),
    ("broker-readiness-persist-public", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'Array(identity.verificationKey.encoded.utf8)', 'Array(identity.startupKey.expose().utf8)',
     "brokerStartupIsVersionedAndOnlyPublicMaterialIsPersisted"),
    ("broker-readiness-required", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'for provider in try requiredProviders(instance, config: config) {', 'for provider in [ProxyProvider]() {',
     "brokerRequiredProofRefusesAMissingBroker"),
    ("broker-readiness-local", "Sources/IsoHost/Runtime/BrokerReadiness.swift",
     'guard try ModelState.loadOrDefault(instance).mode == .remote else { return [] }',
     'guard true else { return [] }', "brokerRequirementsUseEffectiveRemoteUpstreamsWithoutResolvingSecrets"),
    ("broker-readiness-cleanup", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     'if unlink(publicKey) != 0 && errno != ENOENT {', 'if false {',
     "brokerStartupIsVersionedAndOnlyPublicMaterialIsPersisted"),
    ("filtered-readiness-signature", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'return key.value.isValidSignature(signature, for: Data(message.utf8))',
     'return true', "filteredReadinessRejectsForgeryReplayAndFraming"),
    ("filtered-readiness-persist-public", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'Array(verificationKey.encoded.utf8)', 'Array(startupKey.expose().utf8)',
     "filteredReadinessPersistsOnlyPublicMaterialEvenWhenWorkspaceCopiesIt"),
    ("filtered-readiness-nonce", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'reply.nonce == nonce,', 'true,', "filteredReadinessRejectsForgeryReplayAndFraming"),
    ("filtered-readiness-boot", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'reply.bootID == policy.bootID,', 'true,', "filteredReadinessRejectsForgeryReplayAndFraming"),
    ("filtered-readiness-policy", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'reply.policyHash == policy.policyHash,', 'true,', "filteredReadinessRejectsForgeryReplayAndFraming"),
    ("filtered-readiness-version", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'reply.version == 2,', 'true,', "filteredReadinessRejectsForgeryReplayAndFraming"),
    ("filtered-readiness-framing", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'headers[1] == "Content-Length: \\(body.count)",', 'true,',
     "filteredReadinessRejectsForgeryReplayAndFraming"),
    ("filtered-readiness-read-error", "Sources/IsoHost/Runtime/FilteredReadiness.swift",
     'guard let bytes = try StateStore.readControlFile(path) else {',
     'guard let bytes = try? StateStore.readControlFile(path) else {',
     "filteredReadinessControlErrorsDoNotMasqueradeAsAbsence"),
    ("filtered-readiness-legacy-key-cleanup", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     'instance.directory + "/egress-readiness-key",', '',
     "stoppingEgressClearsCurrentAndLegacyBootPolicy"),
    ("filtered-readiness-cleanup", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     'FilteredReadiness.keyPath(instance),', '',
     "stoppingEgressClearsCurrentAndLegacyBootPolicy"),
    ("filtered-handoff-protocol", "Sources/IsoHost/Runtime/FilteredHandoff.swift",
     "guard advertisedProtocol == RuntimeProtocol.bootIdentity else { return .runtimeIncompatible }",
     "if false { return .runtimeIncompatible }", "filteredHandoffBindsProtocolPolicyAndOwner"),
    ("filtered-handoff-policy", "Sources/IsoHost/Runtime/FilteredHandoff.swift",
     'guard recordedPolicyHash == wantedPolicyHash, !wantedPolicyHash.isEmpty else {',
     'guard true else {', "filteredHandoffBindsProtocolPolicyAndOwner"),
    ("filtered-handoff-owner", "Sources/IsoHost/Runtime/FilteredHandoff.swift",
     "guard ownerMatches else { return .ownerChanged }", "if false { return .ownerChanged }",
     "filteredHandoffBindsProtocolPolicyAndOwner"),
    ("network-policy-required", "Sources/IsoHost/Runtime/NetworkPolicy.swift",
     'guard let recorded = try load(instance) else {',
     'let recorded = try load(instance) ?? make(config)\n    if false {',
     "networkPolicyRequiresCreationRecordInEveryMode"),
    ("network-policy-fixed-mode", "Sources/IsoHost/Runtime/NetworkPolicy.swift",
     'guard recorded.mode == config.egress.rawValue else {', 'guard true else {',
     "networkPolicyPreservesModeAndFreezesRunningAllowlist"),
    ("network-policy-running-hosts", "Sources/IsoHost/Runtime/NetworkPolicy.swift",
     'guard recorded.allowedHosts == make(config).allowedHosts else {', 'guard true else {',
     "networkPolicyPreservesModeAndFreezesRunningAllowlist"),
    ("network-policy-crashed-boot", "Sources/IsoHost/Lifecycle/AppleLifecycle.swift",
     '      try NetworkPolicy.enforce(instance, config: config)', '      break',
     "stoppedBootReplacesAllowlistOnlyAfterSuccessfulBoot"),
    ("network-policy-premature-commit", "Sources/IsoHost/Lifecycle/AppleLifecycle.swift",
     '    let trust: HostKeyTrust = sidecar.reenrollHostKey ? .reenrollAfterRestore : .requirePin',
     '    try NetworkPolicy.save(config, instance)\n'
     '    let trust: HostKeyTrust = sidecar.reenrollHostKey ? .reenrollAfterRestore : .requirePin',
     "stoppedBootReplacesAllowlistOnlyAfterSuccessfulBoot"),
    ("network-policy-boot-commit", "Sources/IsoHost/Lifecycle/AppleLifecycle.swift",
     '      try NetworkPolicy.save(config, instance)', '',
     "stoppedBootReplacesAllowlistOnlyAfterSuccessfulBoot"),
    ("network-policy-hash", "Sources/IsoHost/Runtime/NetworkPolicy.swift",
     "record.policyHash == hash(mode: record.mode, hosts: record.allowedHosts)", "true",
     "networkPolicyVerifiesItsCanonicalHash"),
    ("network-policy-hosts", "Sources/IsoHost/Runtime/NetworkPolicy.swift",
     'record.allowedHosts == Set(record.allowedHosts).sorted(),\n'
     '      record.allowedHosts.allSatisfy({ (try? ExactHostname($0))?.rawValue == $0 }),',
     'true,', "networkPolicyRejectsNoncanonicalOrInvalidHostsAndModes"),
    ("network-policy-mode", "Sources/IsoHost/Runtime/NetworkPolicy.swift",
     'mode == .filtered || record.allowedHosts.isEmpty,', 'true,',
     "networkPolicyRejectsNoncanonicalOrInvalidHostsAndModes"),
    ("filtered-boot-policy-cleanup", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     'FilteredHandoff.policyPath(instance), instance.directory + "/egress-boot-id",',
     'instance.directory + "/egress-boot-id",',
     "stoppingEgressClearsCurrentAndLegacyBootPolicy"),
    ("filtered-boot-policy-empty", "Sources/IsoHost/Runtime/FilteredHandoff.swift",
     'guard !policy.bootID.isEmpty, !policy.policyHash.isEmpty else {', 'guard true else {',
     "filteredBootPolicyIsAtomicBoundedAndDoesNotAdoptLegacyBootFiles"),
    ("filtered-boot-policy-read-error", "Sources/IsoHost/Runtime/FilteredHandoff.swift",
     'guard let bytes = try StateStore.readControlFile(path) else { return nil }',
     'guard let bytes = try? StateStore.readControlFile(path) else { return nil }',
     "filteredBootPolicyIsAtomicBoundedAndDoesNotAdoptLegacyBootFiles"),
    ("filtered-boot-policy-schema", "Sources/IsoHost/Runtime/FilteredHandoff.swift",
     'policy.schemaVersion == 1, policy.backend == StateSchema.backend', 'true',
     "filteredBootPolicyIsAtomicBoundedAndDoesNotAdoptLegacyBootFiles"),
    ("filtered-handoff-boot", "Sources/IsoHost/Runtime/FilteredHandoff.swift",
     "guard recordedBootID == liveBootID else { return .bootChanged }",
     "if false { return .bootChanged }",
     "filteredHandoffRefusesAChangedBoot"),
    ("instance-unhealthy-typed", "Sources/IsoHost/Runtime/AppleBackend.swift",
     "throw InstanceUnhealthy(instance.name, cause: failure.cause)",
     "throw Self.unreachable(instance.name, cause: failure.cause)",
     "filteredReadinessFailureIsUnhealthyWhileGateFailuresStayErrors"),
    ("instance-unhealthy-readiness-only", "Sources/IsoHost/Runtime/InstanceHealth.swift",
     "do { return try body() } catch { throw ReadinessFailure(cause: error) }",
     "return try body()", "filteredReadinessFailureIsUnhealthyWhileGateFailuresStayErrors"),
    ("instance-health-host-proof", "Sources/IsoHost/Runtime/AppleBackend.swift",
     "guard config.egress == .filtered else { return .running }", "if true { return .running }",
     "filteredReadinessFailureIsUnhealthyWhileGateFailuresStayErrors"),
    ("instance-unhealthy-code", "Sources/IsoCLI/Support/MachineErrors.swift",
     "return (.instanceUnhealthy, .instance(name: unhealthy.instance.rawValue))",
     "return (.operationFailed, nil)", "errorsClassifyAlongTheContextChain"),
    ("startup-forwards-before-proof", "Sources/IsoHost/Lifecycle/ProjectLifecycle.swift",
     "    try PortForwards.save(forwardSet, instance, diagnostics: diagnostics)\n    try GuestEnvState(entries: options.boot",
     "    try forwards.spawn(instance, target, forwardSet)\n    try GuestEnvState(entries: options.boot",
     "filteredStartSpawnsNoPortForwardBeforeReadiness"),
    ("restart-forwards-before-proof", "Sources/IsoHost/Lifecycle/ProjectLifecycle.swift",
     "    try GuestEnvState(entries: guestEnvironment).save(instance, diagnostics: diagnostics)\n    let proven",
     "    try forwards.spawn(instance, target, forwardSet)\n    try GuestEnvState(entries: guestEnvironment).save(instance, diagnostics: diagnostics)\n    let proven",
     "filteredStartSpawnsNoPortForwardBeforeReadiness"),
    ("up-reuse-unproven", "Sources/IsoHost/Lifecycle/UpWorkflow.swift",
     "    return try lifecycle.backend.asRunning(instance) != nil",
     "    return true", "filteredStartSpawnsNoPortForwardBeforeReadiness"),
    ("model-tunnel-alive", "Sources/IsoHost/Runtime/ModelTunnelReadiness.swift",
     "        TunnelIdentity.verify(\n          instance, ProxyLauncher.modelTunnelName(port), address: scope.address)",
     "        true", "filteredProofRequiresEveryStartedModelTunnel"),
    ("model-tunnel-target", "Sources/IsoHost/Runtime/ModelTunnelReadiness.swift",
     "case .guest(let target): recorded == ProxyLauncher.modelTunnelSpec(target, tunnel)",
     "case .guest: true", "filteredProofRequiresEveryStartedModelTunnel"),
    ("tunnel-identity-control-path", "Sources/IsoHost/Guest/TunnelIdentity.swift",
     "&& zip(arguments, arguments.dropFirst()).contains { $0 == \"-S\" && $1 == controlPath }",
     "", "tunnelIdentityNamesOnlyTheRecordedMaster"),
    ("tunnel-identity-pid-file", "Sources/IsoHost/Guest/TunnelIdentity.swift",
     "      Int32(String(decoding: bytes, as: UTF8.self).trimmingUnicodeWhitespace()) == identity.pid,\n",
     "      !bytes.isEmpty,\n", "tunnelIdentityNamesOnlyTheRecordedMaster"),
    ("tunnel-identity-address", "Sources/IsoHost/Guest/TunnelIdentity.swift",
     "address.map({ $0 == identity.address }) ?? true,", "true,",
     "tunnelIdentityNamesOnlyTheRecordedMaster"),
    ("tunnel-identity-cleanup", "Sources/IsoHost/Guest/ProxyLifecycle.swift",
     "    unlink(TunnelIdentity.path(instance, Self.modelTunnelName(port)))\n", "",
     "tunnelIdentityNamesOnlyTheRecordedMaster"),
    ("session-supervision-cancel", "Sources/IsoHost/Guest/GuestSession.swift",
     "    supervised.isCancelled = { supervisor.lost }\n", "",
     "supervisedWorkloadEndsWhenItsProofIsLost"),
    ("session-supervision-recheck", "Sources/IsoHost/Guest/GuestSession.swift",
     "          try revalidate()\n          pending = nil", "          pending = nil",
     "supervisedWorkloadEndsWhenItsProofIsLost"),
    ("session-supervision-filtered", "Sources/IsoHost/Guest/GuestSession.swift",
     "    running.handoffIdentity == nil ? nil : interval", "    nil",
     "onlyFilteredWorkloadsAreSupervised"),
    ("egress-lease-supervision-lost", "Sources/IsoHost/Runtime/EgressLease.swift",
     "      return companionMisses < Self.missLimit && tunnelMisses < Self.missLimit",
     "      return true", "egressLeaseSupervisesOnlyWhatItHasSeen"),
    ("egress-lease-supervision-transient", "Sources/IsoHost/Runtime/EgressLease.swift",
     "      return companionMisses < Self.missLimit && tunnelMisses < Self.missLimit",
     "      return companionMisses < 1 && tunnelMisses < 1", "egressLeaseSupervisesOnlyWhatItHasSeen"),
    ("egress-lease-close-forwards", "Sources/IsoHost/Runtime/EgressLease.swift",
     "        arguments: [\"-O\", \"exit\", \"-o\", \"ControlPath=\\(control)\", \"iso-forwards\"],",
     "        arguments: [\"-V\"],", "closingForwardsExitsTheMasterAndRemovesItsSocket"),
    ("egress-lease-supervision-startup", "Sources/IsoHost/Runtime/EgressLease.swift",
     "      companionSeen = companionSeen || companionAlive\n      tunnelSeen = tunnelSeen || tunnelAlive\n",
     "      companionSeen = true\n      tunnelSeen = true\n", "egressLeaseSupervisesOnlyWhatItHasSeen"),
    ("egress-lease-nosigpipe", "Sources/IsoHost/Runtime/EgressLease.swift",
     "    fcntl(fd, F_SETNOSIGPIPE, 1) == 0", "    fd >= 0",
     "leaseRenewalFailsWithoutSIGPIPEOnceTheCompanionIsGone"),
    ("session-supervision-two-strikes", "Sources/IsoHost/Guest/GuestSession.swift",
     "          guard pending != nil else {", "          guard true else {",
     "supervisedWorkloadEndsWhenItsProofIsLost"),
]


TOP_LEVEL_SKIPS = {".git", ".build", "target", "iso-proxy", "iso-egress"}


def skip_top_level(directory, names):
    if Path(directory) == ROOT / "iso-sandbox":
        return set(names) & {".build", ".swiftpm"}
    if Path(directory) != ROOT:
        return set()
    return {name for name in names if name in TOP_LEVEL_SKIPS or name.startswith((".build-", "mutants.out"))}


def test_package(relative):
    return "iso-sandbox" if relative.startswith("iso-sandbox/") else "."


def run_tests(scratch, test_filter, package="."):
    argv = ["swift", "test", "--force-resolved-versions"]
    if package != ".":
        argv += ["--package-path", str(scratch / package), "--no-parallel"]
    return subprocess.run(
        argv + ["--filter", test_filter],
        cwd=scratch, capture_output=True, text=True, timeout=1800,
    )


def passed_count(result):
    return result.stdout.count("\u2714 Test ") + result.stdout.count("✔ Test ")


def failed_a_test(result):
    """A test ran and failed — not a compile error, which proves nothing."""
    return result.returncode != 0 and ("✘ Test " in result.stdout or "\u2718 Test " in result.stdout)


def run_fault(scratch, fault, verbose):
    ident, relative, original, replacement, test_filter = fault
    path = scratch / relative
    source = path.read_text()
    if original not in source:
        return f"{ident}: anchor not found in {relative}"
    path.write_text(source.replace(original, replacement, 1))
    try:
        # Concurrency faults are timing dependent; retry to make detection robust.
        attempts = 5 if ident == "config-writer-lock" else 1
        for _ in range(attempts):
            result = run_tests(scratch, test_filter, test_package(relative))
            if verbose:
                print(result.stdout[-2000:], result.stderr[-2000:])
            if failed_a_test(result):
                return None
            if result.returncode != 0:
                return f"{ident}: the fault does not compile, so it proves nothing ({test_filter})"
        return f"{ident}: tests still pass with the fault ({test_filter})"
    finally:
        path.write_text(source)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--only", choices=[f[0] for f in FAULTS], help="run a single fault id")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()
    faults = [f for f in FAULTS if not args.only or f[0] == args.only]
    with tempfile.TemporaryDirectory(prefix="iso-fault-") as directory:
        scratch = Path(directory) / "iso"
        shutil.copytree(
            ROOT, scratch,
            # Skip build output and unused companion packages, not similarly
            # named fixtures or fuzz/Targets (a package target).
            ignore=skip_top_level,
        )
        # Control: every filter passes unmodified, so a failure under a fault
        # is the fault's effect and not a broken copy or a flaky test.
        for package in sorted({test_package(f[1]) for f in faults}):
            filters = "|".join(sorted({f[4] for f in faults if test_package(f[1]) == package}))
            control = run_tests(scratch, filters, package)
            if control.returncode != 0 or not passed_count(control):
                print(control.stdout[-3000:], control.stderr[-3000:], file=sys.stderr)
                print(f"control run failed: the unmodified {package} copy does not pass", file=sys.stderr)
                return 2
        survivors = []
        for fault in faults:
            outcome = run_fault(scratch, fault, args.verbose)
            status = "detected" if outcome is None else ("ANCHOR MISSING" if "anchor not found" in outcome else "SURVIVED")
            print(f"{fault[0]}: {status}", flush=True)
            if outcome:
                survivors.append(outcome)
    for survivor in survivors:
        print(survivor, file=sys.stderr)
    return 1 if survivors else 0


if __name__ == "__main__":
    sys.exit(main())
